### ISSUE TITLE
qc_report task not recognizing arguments

### ISSUE THREAD

**Issue by xiaofanjin** [ENCODE-DCC/chip-seq-pipeline2#101]
I'm running into issues at the qc_report task in the workflow - the errors look slightly different if I'm running using conda environment or singularity container. Using the latest singularity image, I get:

`STDERR_CONTENTS=
Unknown option: --
usage: python3 [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.`

with conda:
`STDERR_CONTENTS=
usage: ENCODE Final QC report/JSON generator. [...]
ENCODE Final QC report/JSON generator.: error: unrecognized arguments: --xcor-pe-trim-bp 50 --xcor-subsample-reads 15000000`

[output_singularity.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3774263/output_singularity.txt)
[output_conda.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3774264/output_conda.txt)

Not sure if the argument flags have changed between different versions?

**Comment by leepc12** [comment]
If you updated the pipeline, you should also update your Conda env.
```
$ bash scripts/update_conda_env.sh
```

**Comment by xiaofanjin** [comment]
thanks, that fixed it
