### ISSUE TITLE
ERROR: Finished parsing without consuming all tokens

### ISSUE THREAD

**Issue by CRichard21** [ENCODE-DCC/chip-seq-pipeline2#104]
Hello,

I have a problem during processing the pipeline. The issue is :

[Caper] Validating WDL/input JSON with womtool...
[Caper] Error (womtool): WDL or input JSON is invalid.

with my own .json file but also with "template.full.json" you provide.
This issue is the same on a local computer or on a SGE cluster.

- OS : Ubuntu 16.04 and SGE cluster
- caper 0.5.4

Thanks in advance

**Comment by leepc12** [comment]
Please try with Caper>=0.6.0. There was a bug in input-JSON validation in 0.5.4 and 0.5.5.

Also fixed some wrong parameters in the full template and will be applied to the next release.
See this commit 746c791c5db47454ab55f2cd8c6f8f767d2ae987.

**Comment by dearxxj** [comment]
Hi, just wondering any update on this? I have the same problem with Caper 0.6.3 and womtool-47.jar with either template.json or template.full.json. I just installed the latest Github chip-seq-pipeline2 pipeline today. Thanks!

**Comment by leepc12** [comment]
@dearxxj : see the error message and it will show which part of the input JSON is wrong.

**Comment by dearxxj** [comment]
It doesn't show which part is wrong, just like OP's original question. My input JSON is the template.json in the git repo. To do a test run, I didn't modify it, but I still get the error.

> [CaperURI] copying skipped, target: ~/.caper/womtool_jar/womtool-47.jar
[Caper] Validating WDL/input JSON with womtool...
[Caper] Error (womtool): WDL or input JSON is invalid.
srun: error: hpc10: task 0: Exited with exit code 1

**Comment by leepc12** [comment]
Does your input JSON file exist? Use an absolute path for the input JSON in "caper run" command line.

**Comment by dearxxj** [comment]
Problem solved! Tried many ways but forgot to check this... Thank you for spending time helping me out!
