### ISSUE TITLE
Why use SPP as default TF peak caller instead of MACS?

### ISSUE THREAD

**Issue by haowenz** [ENCODE-DCC/chip-seq-pipeline2#109]
Hi,

It took more than 30h to finish the pipeline even on a normal size TF ChIP-seq dataset from ENCODE project. And it seems that most of the time are spent on running SPP to call peaks. I also found that if I set the peak caller to MACS, it only took about 3h. MACS looks like a popular peak caller which have already got thousands of citations. Could you kindly tell me why the pipeline uses SPP rather than MACS?

Thanks,
Haowen

**Comment by akundaje** [comment]
MACS2 is fast but the reproducibility across replicates tends to be less
reliable than SPP. We typically get better sensitivity and specificity of
reproducible IDR peaks with SPP in our benchmarks. So from the consortium's
perspective we have stuck to SPP for TFs. You should feel free to use MACS2
if you like. That is why we included it in the pipeline for those who do
not want to put up with the slow speed of SPP.

-Anshul.
