### ISSUE TITLE
libreadline problem

### ISSUE THREAD

**Issue by Fnyasimi** [ENCODE-DCC/chip-seq-pipeline2#110]
**Describe the bug**
The workflow breaks when it gets to running the `encode_task_xcor.py` script and on investigation it is cause by missing `libreadline.so.6` which is not supported by my version of ubuntu. Kindly is there a way to make the pipeline work with `libreadline.so.7`?

**OS/Platform**
- OS/Platform: Ubuntu 18.04
- Conda version: 4.7.12
- Pipeline version: v1.3.4
- Caper version: v0.6.1

**Input JSON file**
ENCSR000DYI_subsampled_chr19_only_caper.json.

**Error log**
error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory.
```
chip.xcor Failed. SHARD_IDX=1, RC=1, JOB_ID=6989, RUN_START=2019-11-22T09:28:13.001Z, RUN_END=2019-11-22T09:28:24.308Z, STDOUT=/home/festo/Documents/MARStool/try2/chip/8e8159b1-fe67-41da-840c-8d693897e9df/call-xcor/shard-1/attempt-2/execution/stdout, STDERR=/home/festo/Documents/MARStool/try2/chip/8e8159b1-fe67-41da-840c-8d693897e9df/call-xcor/shard-1/attempt-2/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_xcor.py", line 156, in <module>
    main()
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_xcor.py", line 144, in main
    args.chip_seq_type, args.exclusion_range_min, args.exclusion_range_max)
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_xcor.py", line 105, in xcor
    run_shell_cmd(cmd1)
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=7018, PGID=7018, RC=127
STDERR=/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/R/bin/exec/R: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
STDOUT=

```

**Comment by leepc12** [comment]
This looks like Conda's issue. I tried to install pipeline's Conda env with libreadline6 but failed. Conda couldn't resolve conflicts with other softwares. Can you install libreadline6-dev somehow on your system and try again?

```
$ sudo apt-get install libreadline6-dev
```

**Comment by Fnyasimi** [comment]
`libreadline6` is not supported by Ubuntu 18.04 and the above command doesn't install it. However, after reading and following through this [page](https://utcc.utoronto.ca/~cks/space/blog/linux/Ubuntu1804ReadlineMess?showcomments#comments) I managed to set it up.

I tried the workflow again and ran into new errors
```
File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/bin/caper", line 13, in <module>
    main()
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/caper/caper.py", line 1266, in main
    c.run()
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/caper/caper.py", line 272, in run
    json.loads(fp.read()))
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Any help on that?

**Comment by leepc12** [comment]
Please upload your Caper conf and input JSON. Check if your input JSON is valid.

**Comment by Fnyasimi** [comment]
Caper conf
```
backend=local

tmp-dir="/home/festo/Documents/MARStool/caper_tmp"
```

Input JSON
I am using the test `ENCSR000DYI_subsampled_chr19_only_caper.json` file to ensure the pipeline is fully working before I can proceed to working on other data.

**Comment by leepc12** [comment]
You can ignore this error since it  occurred when troubleshooting the failure itself (when parsing the final output log `metadata.json`).  Please attach your full screen log from Caper.

**Comment by Fnyasimi** [comment]
Hi Lee thanks for the assistance somehow I managed to by pass the error and finished the step successfully.

I moved on to the next step using `croo` my command is as below;
`croo ./chip/33f2a043-862a-4dc5-bf9a-418685787b6b/metadata.json`

I ran into this error below
```
[CaperURI] write to local, target: /home/festo/Documents/MARStool/try2/croo.filetable.33f2a043-862a-4dc5-bf9a-418685787b6b.tsv, size: 26506
Error: _tmp_.dot: syntax error in line 349 near '/'
Traceback (most recent call last):
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/bin/croo", line 13, in <module>
    main()
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/croo/croo.py", line 301, in main
    co.organize_output()
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/croo/croo.py", line 188, in organize_output
    report.save_to_file()
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/croo/croo_html_report.py", line 72, in save_to_file
    body += self._task_graph.get_html_body_str()
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/croo/croo_html_report_task_graph.py", line 49, in get_html_body_str
    svg_contents = self.__make_svg()
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/croo/croo_html_report_task_graph.py", line 91, in __make_svg
    filename=tmp_dot)
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/graphviz/files.py", line 209, in render
    quiet=quiet)
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/graphviz/backend.py", line 208, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/graphviz/backend.py", line 174, in run
    output=out, stderr=err)
graphviz.backend.CalledProcessError: Command '['dot', '-Tsvg', '-O', '_tmp_.dot']' returned non-zero exit status 1. [stderr: b"Error: _tmp_.dot: syntax error in line 349 near '/'\n"]
```

Any idea what is the cause?

**Comment by leepc12** [comment]
Can you send me that `/home/festo/Documents/MARStool/try2/_tmp_.dot` file?

**Comment by Fnyasimi** [comment]
The json file is used can be found [here](https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/master/example_input_json/caper/ENCSR000DYI_subsampled_chr19_only_caper.json)

Caper config
```
backend=local
tmp-dir="/home/festo/Documents/MARStool/caper_tmp"
db=mysql
mysql-db-port=3308
```
Help with this error its showing up many times in my runs.

---------------
One run was successful I don't  know how and I tried using `croo` command as below;
`croo ./chip/33f2a043-862a-4dc5-bf9a-418685787b6b/metadata.json`

I ran into this error below
```
[CaperURI] write to local, target: /home/festo/Documents/MARStool/try2/croo.filetable.33f2a043-862a-4dc5-bf9a-418685787b6b.tsv, size: 26506
Error: _tmp_.dot: syntax error in line 349 near '/'
Traceback (most recent call last):
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/bin/croo", line 13, in <module>
    main()
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/croo/croo.py", line 301, in main
    co.organize_output()
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/croo/croo.py", line 188, in organize_output
    report.save_to_file()
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/croo/croo_html_report.py", line 72, in save_to_file
    body += self._task_graph.get_html_body_str()
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/croo/croo_html_report_task_graph.py", line 49, in get_html_body_str
    svg_contents = self.__make_svg()
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/croo/croo_html_report_task_graph.py", line 91, in __make_svg
    filename=tmp_dot)
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/graphviz/files.py", line 209, in render
    quiet=quiet)
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/graphviz/backend.py", line 208, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/graphviz/backend.py", line 174, in run
    output=out, stderr=err)
graphviz.backend.CalledProcessError: Command '['dot', '-Tsvg', '-O', '_tmp_.dot']' returned non-zero exit status 1. [stderr: b"Error: _tmp_.dot: syntax error in line 349 near '/'\n"]
```

Any idea what is the cause?

**Comment by leepc12** [comment]
That looks like a parsing error for new line `\n`.
[chip.croo.json.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3928978/chip.croo.json.txt)
Can you download this file rename it to `.json` and use this file for croo command line `--out-def-json`?
```
$ croo ... --out-def-json [DOWNLOADED_JSON_FILE]
```

**Comment by Fnyasimi** [comment]
I have downloaded it and tried it again still getting the same error

**Comment by leepc12** [comment]
I think two problems are mixed up?

1) Croo issue

Didn't it fix the croo dot problem? Do you still get this error? Can you upload your tmp.dot?
```
graphviz.backend.CalledProcessError: Command '['dot', '-Tsvg', '-O', '_tmp_.dot']' returned non-zero exit status 1. [stderr: b"Error: _tmp_.dot: syntax error in line 349 near '/'\n"]
```

2) Caper issue

Just ignore this Caper JSON error.
```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Fnyasimi** [comment]
1. Croo Issue
Here is the [tmp.dot file](https://github.com/Fnyasimi/Marstool/blob/master/_tmp_.dot) after running
`croo metadata.json --out-def-json chip.croo.json`

2. Caper Issue
How do I ensure my analysis keeps going after encountering this error, as of now this error stops the analysis.

**Comment by leepc12** [comment]
1. Your dot file is very helpful. Can you also upload your `metadata.json` file? You may need to rename it to `.txt` or something.

2. That error happens in the troubleshooting part of Caper, which takes place after pipeline is done (whether it was successful or not). So that error is not the reason for the pipeline failure.

**Comment by Fnyasimi** [comment]
1. The metadata file is [here](https://github.com/Fnyasimi/Marstool/blob/master/metadata.txt)

2. When I get that error I cant parse the metadata file using `croo`. I get the error below
```
Traceback (most recent call last):
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/bin/croo", line 13, in <module>
    main()
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/croo/croo.py", line 299, in main
    soft_link=args['method'] == 'link')
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/croo/croo.py", line 52, in __init__
    self._cm = CromwellMetadata(self._metadata)
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/croo/cromwell_metadata.py", line 100, in __init__
    self.__parse_calls(self._metadata_json['calls'])
  File "/home/festo/miniconda3/envs/encode-chip-seq-pipeline/lib/python3.7/site-packages/croo/cromwell_metadata.py", line 179, in __parse_calls
    all_outputs=tuple(out_files),
TypeError: 'NoneType' object is not iterable
```

**Comment by leepc12** [comment]
1 Failed due to escaped slashes in your input JSON. This seems to be derived from Caper's variable `tmp-dir` defined in your Caper conf file `~/.caper/default.conf`.
```
{
    "chip.pipeline_type": "tf",
    "chip.genome_tsv": "/home/festo/Documents/MARStool/try2/\"/home/festo/Documents/MARStool/caper_tmp\"/5c2c89bb8ec90798b9fcec36a87cc035/hg38_chr19_chrM_caper.local.tsv",
    "chip.fastqs_rep1_R1": [
        "/home/festo/Documents/MARStool/try2/\"/home/festo/Documents/MARStool/caper_tmp\"/41d3a8658bf4f565c08290e386fddccf/rep1.subsampled.25.fastq.gz"
    ],
    "chip.fastqs_rep2_R1": [
        "/home/festo/Documents/MARStool/try2/\"/home/festo/Documents/MARStool/caper_tmp\"/0d5b102d7f21dd009798ae9b2c318b65/rep2.subsampled.20.fastq.gz"
    ],
    "chip.ctl_fastqs_rep1_R1": [
        "/home/festo/Documents/MARStool/try2/\"/home/festo/Documents/MARStool/caper_tmp\"/f4dba75d4430f4702a75554c44265119/ctl1.subsampled.25.fastq.gz"
    ],
    "chip.ctl_fastqs_rep2_R1": [
        "/home/festo/Documents/MARStool/try2/\"/home/festo/Documents/MARStool/caper_tmp\"/7a610dd5397c45a806678efaad824abf/ctl2.subsampled.25.fastq.gz"
    ],
    "chip.paired_end": false,
    "chip.always_use_pooled_ctl": true,
    "chip.title": "ENCSR000DYI (subsampled 1/25, chr19_chrM only)",
    "chip.description": "CEBPB ChIP-seq on human A549 produced by the Snyder lab"
}
```

I think you have quotes like `"` in your Caper conf `~/.caper/default.conf`? Something like
```
tmp-dir="/home/festo/Documents/MARStool/caper_tmp"
```
This will lead to errors since Python ConfigParse (CONFIG INI parser) does not automatically remove leading/trailing quotes. Please remove these quotes in your conf file.

I will auto-strip those quotes in the next release of Caper. Until then, edit your `metadata.json` file.
Replace 
```
/home/festo/Documents/MARStool/try2/\"/home/festo/Documents/MARStool/caper_tmp\"
```
with an actual absolute path for that directory. And then run Croo with that `metadata.json`.

**Comment by leepc12** [comment]
1. Update Caper to auto-strip quotes in conf file.

2.  Updated Croo to 0.3.3.

Please `pip install croo==0.3.3` and try again
I still wonder why this error occurred. I tested with your `metadata.json` but I didn't get that error.

**Comment by Fnyasimi** [comment]
Thank you Lee these updates are working fine with the test files I hope it will be well with real datasets.

I have tried my own json file and it has a memory error with bowtie, see below;
```
chip.align_ctl Failed. SHARD_IDX=0, RC=1, JOB_ID=45787, RUN_START=2019-12-05T11:25:00.187Z, RUN_END=2019-12-05T15:50:50.535Z, STDOUT=/home/fnyasimi/Marstools/paired_testrun/chip/da292a55-abb0-4a68-b1c1-66a8d7a7b4ea/call-align_ctl/shard-0/attempt-2/execution/stdout, STDERR=/home/fnyasimi/Marstools/paired_testrun/chip/da292a55-abb0-4a68-b1c1-66a8d7a7b4ea/call-align_ctl/shard-0/attempt-2/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/home/fnyasimi/.conda/envs/encode-chip-seq-pipeline/bin/encode_task_bowtie2.py", line 192, in <module>
    main()
  File "/home/fnyasimi/.conda/envs/encode-chip-seq-pipeline/bin/encode_task_bowtie2.py", line 166, in main
    args.out_dir)
  File "/home/fnyasimi/.conda/envs/encode-chip-seq-pipeline/bin/encode_task_bowtie2.py", line 101, in bowtie2_pe
    run_shell_cmd(cmd)
  File "/home/fnyasimi/.conda/envs/encode-chip-seq-pipeline/bin/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=45856, PGID=45856, RC=1
STDERR=[bam_sort_core] merging from 22 files and 1 in-memory blocks...
STDOUT=
```
Where should I tweak the memory size or how do I solve the error?

**Comment by leepc12** [comment]
Increase `chip.align_mem_mb` in your input JSON. It's 20000 by default.

**Comment by Fnyasimi** [comment]
Thank you for that. 

Kindly help me with the `chip.ctl` right parameters to use in this situations below and when do I use `chip.always_use_pooled_ctl`?

1. All biological replicates don't have controls in SE reads.

2. One of the biological replicate doesn't have a control in SE reads.

3. In PE R2 doesn't have a control in one or more biological replicates.

4. Both reads in PE (R1 and R2) of one biological replicate don't have controls.

5. All biological replicates in PE don't have controls.

**Comment by leepc12** [comment]
`if number_of_control >=2 and chip.always_use_pooled_ctl is True` then the pipeline always uses a pooled control for all biological IP replicate. Otherwise pipeline tries to match IP replicate index and control index. Pipeline also compares read depth between controls. See documentation for `chip.ctl_depth_ratio` parameter.

Endedness of a control doesn't matter. You can use mixed endedness for any IP replicate/controls if you correctly define endedness for each. Check `chip.paired_ends` and `chip.ctl_paired_ends` parameters.

If there are 2>= control replicates defined, then

**Comment by Fnyasimi** [comment]
Thank you Lee

What is the maximum number of technical replicates per sample?

**Comment by leepc12** [comment]
There is no limit. All technical replicates will be merged into one bio replicate.

**Comment by Fnyasimi** [comment]
I am interested in running an analysis with a total of 10 replicates each with its control, kindly guide me on the optimum memory and number of cores tweak in the input json file to avoid memory related errors.

Is it possible to run the analysis without controls at all? And if yes are there options I need to define?

**Comment by leepc12** [comment]
Amount of resources required is roughly proportional to the size of FASTQs. About 2 (or 3) x "size of the largest R1 FASTQ" for "chip.align_mem_mb".  Recommended number of cores is like 4 to 8. 

Are they biological replicates from a single experiment? If not, I recommend run a separate pipeline for each replicate. 10 replicates will result in at least 10_C_2 (= 45) + 10 tasks for IDR/overlap analyses.

Whether you need controls or not depends on the peak caller. TF ChIP (chip.pipeline_type in your input JSON == "chip") defaults to use SPP peak caller and Histone one uses MACS2 peak caller. SPP requires controls.

You can use MACS2 peak caller for TF ChIP-seq (set chip.peak_caller in your input JSON as "macs2").

**Comment by Fnyasimi** [comment]
Yes they are biological replicates from a single experiment. How heavy is the IDR analyses computation.

I am doing  TF Chip without controls and if I understood you my json file should be like this;
```
"chip.pipeline_type" : "tf"

"chip.peak_caller" : "macs2"
```

**Comment by leepc12** [comment]
They are actually not heavy like aligning and peak-calling so just give it a try and see if it works. Your input JSON looks good.

**Comment by Fnyasimi** [comment]
I am interested in building a Drosophila genome database. Should I use masked or unmasked reference sequence and do you have a blacklist file for the genome?

I will also appreciate if there is an already build genome database for the same.

Kindly assist links to blacklist files and reference genome you are using.

**Comment by leepc12** [comment]
There is no build genome database for Drosophila. Use unmasked reference genome .fa.gz or .2bit file. We don't have a blacklist for it. Pipeline can work without a blacklist though.

Use this builder.

https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/master/scripts/build_genome_data.sh#L137

**Comment by akundaje** [comment]
We do have blacklists for Drosophila

https://github.com/Boyle-Lab/Blacklist/tree/master/lists

**Comment by leepc12** [comment]
Closing this. Reopen it if you need further assistance.

**Comment by Fnyasimi** [comment]
Thank you for the assistance so far

**Comment by Fnyasimi** [comment]
Hi Lee I am running the pipeline on a hpc which has all the http ports closed and somehow I think the pipeline requires a working connection before its starts executing the analyisis. My question is there a way I can run the pipeline completely offline without internet access?

**Comment by leepc12** [comment]
Caper will try to access the internet if there is any URL in 1) your Caper conf (`~/.caper/default.conf` ) or your input JSON. If you have those URLs, then download them somewhere on your machine. And define locally downloaded ones in those conf/JSON instead of http ones.

If your cluster is partly online, then try this. This command will installed Cromwell/Womtool locally and Caper will work offline.
```
$ caper init [PLATFORM: sge, slurm, local, ...]
```

If your cluster is completely offline then download Cromwell/Womtool 47 from Cromwell's github site and transfer them somewhere on your cluster.
https://github.com/broadinstitute/cromwell/releases/download/47/cromwell-47.jar
https://github.com/broadinstitute/cromwell/releases/download/47/womtool-47.jar

Then define them in Caper's conf file `~/.caper/default.conf`.
```
cromwell=/where/is/your/cromwell-47.jar
womtool=/here/is/your/womtool-47.jar
```

If you use Singularity (`--singularity`) then you may need to build it locally.
```
$ singularity exec docker://quay.io/encode-dcc/chip-seq-pipeline:v1.3.6 echo hello world
```
Find a built image file `.sif` or `.simg` on your CWD or `$SINGULARITY_PULLDIR` or `$SINGULARITY_CACHEDIR`.

Define that image in the Caper command line like:
```
$ caper run chip.wdl ... --singularity YOUR_LOCAL_IMAGE.sif
```

**Comment by Fnyasimi** [comment]
Thank you the definitions above work well, however you did not inform me how to define `croo` 
for this bit
>`[CaperURI] copying from url to local, src: https://storage.googleapis.com/encode-pipeline-output-definition/chip.croo.v3.json`

**Comment by leepc12** [comment]
Try with v4 croo JSON file.
```
$ croo ... --out-def-json https://storage.googleapis.com/encode-pipeline-output-definition/chip.croo.v4.json
```
