### ISSUE TITLE
call-gc-bias error

### ISSUE THREAD

**Issue by yifeisun03** [ENCODE-DCC/chip-seq-pipeline2#112]
Hello:

The pipeline is still running but I just saw the stderr file for the call-gc-bias step is not empty, so I opened it up, it looked like this ( all four output files seem to be written, and stdout has " ALL DONE" int the end), should I worry or change anything, Thanks!

Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/sc/orga/projects/walshm02a/Yifei/bsub/chip-caper/chip/3ec5a3d4-32cc-4a79-877b-6fa71b6e09c4/call-gc_bias/shard-0/tmp.ccb9e018
INFO  2019-12-09 04:56:51 CollectGcBiasMetrics

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    CollectGcBiasMetrics -R /sc/orga/projects/walshm02a/Yifei/bsub/chip-caper/chip/3ec5a3d4-32cc-4a79-877b-6fa71b6e09c4/call-gc_bias/shard-0/inputs/-599812846/GRCh38_no_alt_analysis_set_GCA_000\
001405.15.fasta.gz -I ./A15_CKDL190138594-1a-AK445_HMFLWDSXX_L1_1.merged.nodup.no_rg.bam -O A15_CKDL190138594-1a-AK445_HMFLWDSXX_L1_1.merged.nodup.gc.txt -USE_JDK_DEFLATER TRUE -USE_JDK_INFLATER TRUE -VE\
RBOSITY ERROR -QUIET TRUE -ASSUME_SORTED FALSE -CHART A15_CKDL190138594-1a-AK445_HMFLWDSXX_L1_1.merged.nodup.gcPlot.pdf -S A15_CKDL190138594-1a-AK445_HMFLWDSXX_L1_1.merged.nodup.gcSummary.txt
**********

**OS/Platform**
- OS/Platform: hpc cluster
- Pipeline version: [e.g. v1.3.4]
- Caper version: [e.g. v0.6.1]

**Comment by leepc12** [comment]
Our PICARD command line seems to be in an old style, which will be possibly deprecated in next versions. But we already fixed the version of PICARD so you can simply ignore this warning.
