### ISSUE TITLE
Pipeline fails in spp 

### ISSUE THREAD

**Issue by gevirl** [ENCODE-DCC/chip-seq-pipeline2#120]
**Describe the bug**
A clear and concise description of what the problem is.

**OS/Platform** UGE cluster
- Conda version: 4.8.0
- Pipeline version: v1.3.4
- Caper version:  0.6.2

**Caper configuration file**
backend=sge
sge-pe=serial

tmp-dir=/net/waterston/vol9

**Input JSON file**
{"chip.title":"hmg-20_RW12240_youngadult_1_1","chip.description":"mkudron","chip.pipeline_type":"tf","chip.always_use_pooled_ctl":true,"chip.true_rep_only":false,"chip.enable_count_signal_track":true,"chip.aligner":"bwa","chip.use_bwa_mem_for_pe":true,"chip.align_only":false,"chip.genome_tsv":"/net/waterston/vol9/WS245/WS245.tsv","chip.peak_caller":"spp","chip.fastqs_rep1_R1":["/net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/HMGIP1_371_206_S28_L002_R1_001.fastq.gz"],"chip.fastqs_rep1_R2":["/net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/HMGIP1_371_206_S28_L002_R2_001.fastq.gz"],"chip.fastqs_rep2_R1":["/net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/HMGIP2_359_218_S29_L002_R1_001.fastq.gz"],"chip.fastqs_rep2_R2":["/net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/HMGIP2_359_218_S29_L002_R2_001.fastq.gz"],"chip.paired_ends":[true,true],"chip.ctl_fastqs_rep1_R1":["/net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/HMGinp_347_230_S30_L002_R1_001.fastq.gz"],"chip.ctl_fastqs_rep1_R2":["/net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/HMGinp_347_230_S30_L002_R2_001.fastq.gz"],"chip.ctl_paired_ends":[true]}

output metadata.json
[metadata.json.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/4036088/metadata.json.txt)

caper troubleshoot output
[troubleshoot.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/4036096/troubleshoot.txt)

**Comment by leepc12** [comment]
Please upload two files here.

STDOUT=/net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/chip/50bc7bd0-0741-4ad8-b273-0ed77ada166f/call-call_peak_ppr1/attempt-2/execution/stdout

STDERR=/net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/chip/50bc7bd0-0741-4ad8-b273-0ed77ada166f/call-call_peak_ppr1/attempt-2/execution/stderr

**Comment by gevirl** [comment]
I had to add a txt extension to upload 
[stderr.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/4037620/stderr.txt)


[stdout.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/4037618/stdout.txt)

**Comment by leepc12** [comment]
Your troubleshoot.txt says that
```
chip.call_peak_ppr1 Failed. SHARD_IDX=-1, RC=79, JOB_ID=124738477, RUN_START=2020-01-08T02:33:20.817Z, RUN_END=2020-01-08T02:39:58.413Z, STDOUT=/net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/chip/50bc7bd0-0741-4ad8-b273-0ed77ada166f/call-call_peak_ppr1/attempt-2/execution/stdout, STDERR=/net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/chip/50bc7bd0-0741-4ad8-b273-0ed77ada166f/call-call_peak_ppr1/attempt-2/execution/stderr
STDERR_CONTENTS=
/net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/chip/50bc7bd0-0741-4ad8-b273-0ed77ada166f/call-call_peak_ppr1/attempt-2/execution/script: line 1:  3504 CPU time limit exceeded ( cd /net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/chip/50bc7bd0-0741-4ad8-b273-0ed77ada166f/call-call_peak_ppr1/attempt-2/execution; set -e; if [ 'spp' == 'macs2' ]; then
    python3 $(which encode_task_macs2_chip.py) /net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/chip/50bc7bd0-0741-4ad8-b273-0ed77ada166f/call-call_peak_ppr1/attempt-2/inputs/-718686865/HMGIP1_371_206_S28_L002_R1_001.merged.nodup.pr1.pooled.tagAlign.gz /net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/chip/50bc7bd0-0741-4ad8-b273-0ed77ada166f/call-call_peak_ppr1/attempt-2/inputs/-113443660/HMGinp_347_230_S30_L002_R1_001.merged.nodup.tagAlign.gz --gensz 100286401 --chrsz /net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/chip/50bc7bd0-0741-4ad8-b273-0ed77ada166f/call-call_peak_ppr1/attempt-2/inputs/-1580951513/WS245.chrom.sizes --fraglen 172 --cap-num-peak 300000 --pval-thresh 0.01;
else
    if [ 'spp' == 'spp' ]; then
        python3 $(which encode_task_spp.py) /net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/chip/50bc7bd0-0741-4ad8-b273-0ed77ada166f/call-call_peak_ppr1/attempt-2/inputs/-718686865/HMGIP1_371_206_S28_L002_R1_001.merged.nodup.pr1.pooled.tagAlign.gz /net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/chip/50bc7bd0-0741-4ad8-b273-0ed77ada166f/call-call_peak_ppr1/attempt-2/inputs/-113443660/HMGinp_347_230_S30_L002_R1_001.merged.nodup.tagAlign.gz --fraglen 172 --cap-num-peak 300000 --nth 6;
    else
        python3 /net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/chip/50bc7bd0-0741-4ad8-b273-0ed77ada166f/call-call_peak_ppr1/attempt-2/inputs/-718686865/HMGIP1_371_206_S28_L002_R1_001.merged.nodup.pr1.pooled.tagAlign.gz /net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/chip/50bc7bd0-0741-4ad8-b273-0ed77ada166f/call-call_peak_ppr1/attempt-2/inputs/-113443660/HMGinp_347_230_S30_L002_R1_001.merged.nodup.tagAlign.gz --gensz 100286401 --chrsz /net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/chip/50bc7bd0-0741-4ad8-b273-0ed77ada166f/call-call_peak_ppr1/attempt-2/inputs/-1580951513/WS245.chrom.sizes --fraglen 172 --cap-num-peak 300000 --pval-thresh 0.01; --nth 6;
    fi;
fi; python3 $(which encode_task_post_call_peak_chip.py) $(ls *Peak.gz) --ta /net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/chip/50bc7bd0-0741-4ad8-b273-0ed77ada166f/call-call_peak_ppr1/attempt-2/inputs/-718686865/HMGIP1_371_206_S28_L002_R1_001.merged.nodup.pr1.pooled.tagAlign.gz --regex-bfilt-peak-chr-name '[IVX]+' --chrsz /net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/chip/50bc7bd0-0741-4ad8-b273-0ed77ada166f/call-call_peak_ppr1/attempt-2/inputs/-1580951513/WS245.chrom.sizes --fraglen 172 --peak-type regionPeak --blacklist /net/waterston/vol9/ChipSeqPipeline/hmg-20_RW12240_youngadult_1/chip/50bc7bd0-0741-4ad8-b273-0ed77ada166f/call-call_peak_ppr1/attempt-2/inputs/-1580951513/ce11-blacklist.bed.gz ) > "$out50bc7bd0" 2> "$err50bc7bd0"
```
```
CPU time limit exceeded
```
Increase "chip.call_peak_time_hr" in your input JSON and try again.

**Comment by leepc12** [comment]
Closing this due to long inactivity.
