### ISSUE TITLE
Error while trimming when one fastq file present

### ISSUE THREAD

**Issue by irzhegalova** [ENCODE-DCC/chip-seq-pipeline2#122]
When I have only one file in each rep and they are not gzipped, merging makes int copy with gz extension, however not actually compressing it.
This cause problems while trimming later.

def merge_fastqs(fastqs, end, out_dir):
    """make merged fastqs on $out_dir/R1, $out_dir/R2
    """
    out_dir = os.path.join(out_dir, end)
    mkdir_p(out_dir)
    prefix = os.path.join(out_dir,
                          os.path.basename(strip_ext_fastq(fastqs[0])))
    merged = '{}.merged.fastq.gz'.format(prefix)

    if len(fastqs) > 1:
        cmd = 'zcat -f {} | gzip -nc > {}'.format(
            ' '.join(fastqs),
            merged)
        run_shell_cmd(cmd)
        return merged
    else:
        **return copy_f_to_f(fastqs[0], merged)**

**Comment by leepc12** [comment]
Did you use Conda? If so, please replace line 65-72 (https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/master/src/encode_task_merge_fastq.py#L65).
```
    if len(fastqs) > 1:
        cmd = 'zcat -f {} | gzip -nc > {}'.format(
            ' '.join(fastqs),
            merged)
        run_shell_cmd(cmd)
        return merged
    else:
        return copy_f_to_f(fastqs[0], merged)
```
with
```
    cmd = 'zcat -f {} | gzip -nc > {}'.format(
        ' '.join(fastqs),
        merged)
    run_shell_cmd(cmd)
    return merged
```

You can find this file `encode_task_merge_fastq.py` in your Conda's environment.
```
$ conda activate encode-chip-seq-pipeline
$ which encode_task_merge_fastq.py
```

I will test this on my side too but use the above workaround until it's fixed.

**Comment by irzhegalova** [comment]
Thanks a lot for the reply!
it was more my wish to help you fix it in future versions, not my intentions to ask for help :)
