### ISSUE TITLE
p-val vs fc

### ISSUE THREAD

**Issue by jloupe** [ENCODE-DCC/chip-seq-pipeline2#127]
Hello. Sorry if this is a basic question but I think this is the best place for it. 
In both versions of the AQUAS pipeline, two bigwig files are generated, pval and fold-change. My question is to which one is a more reliable metric for ChIP-seq signal generated at a given locus. Pval is usually much cleaner when viewed on a track browser, but I am worried that this signal-noise ratio is somewhat artificial. If I wanted to generate a table of all peaks with their average signal taken from a bigwig, which bigwig would be most appropriate to use? The narrowPeak files have some signal score information, but I have found it to be an unreliable quantitative measure of the signal for a given peak.
Thank you very much.

**Comment by akundaje** [comment]
If you are visualizing you can and should use the pval tracks for the
reasons you mentioned but if you are performing some analyses that need to
use effect sizes then log(fold change) is more appropriate

Anshul

**Comment by jloupe** [comment]
Great. Thank you Anshul.
