### ISSUE TITLE
Error in the pipeline when running it for histone data

### ISSUE THREAD

**Issue by leonorrib** [ENCODE-DCC/chip-seq-pipeline2#137]
Hello,

I am having problems running the ChIP-seq pipeline. I managed to run it for transcription factor data without issues, but for some reason I can't understand I am having problems for histone data.

Here I am uploading the log file of the execution:
[log.bad.mod.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/4359021/log.bad.mod.txt)

And an example of json file I use when running the pipeline with caper in my local server:
[H3K4me3-condition.json.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/4359044/H3K4me3-condition.json.txt)

The command I use to run the pipeline is:
caper run $wdl -i $json --db "file" --out-dir $outdir > $outdir/log.txt 2> $outdir/err.txt

Best regards,
Leonor

**Comment by leepc12** [comment]
Did you activate conda environment before running it?

**Comment by leonorrib** [comment]
Yes, I do. I run the commands below:
source /home/lrib/miniconda3/bin/activate
conda activate encode-chip-seq-pipeline

This allows me to run the pipeline for transcription factors, but not for histone mark data, unfortunately.

**Comment by leepc12** [comment]
You log says that it failed to locate pipeline's task wrapper `.py` files which should be on the conda environment's `bin/` directory.

Run this for debugging. If that doesn't return a path for `encode_task_qc_report.py` file then something is wrong with your Conda's pipeline env. Then re-install the environment (`scripts/uninstall_conda_env.sh` and then install).
```
$ conda activate encode-chip-seq-pipeline
$ which encode_task_qc_report.py
# if the above works then run pipeline
$ caper run ...
```
Make sure the above command works first before running a pipeline.

**Comment by leonorrib** [comment]
Dear Jin,

I did what you suggested. The "which" command finds the script without problems. Then I run the pipeline which ended without completing. Just in case I send the new log file here:
[log.bad3.mod.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/4376795/log.bad3.mod.txt)

**Comment by leepc12** [comment]
Can you try this?
```
$ which encode_task_trim_fastq.py
$ which encode_task_trimmomatic.py
```

**Comment by leonorrib** [comment]
I tried those, too, and it works fine.

Yes, I runned the pipeline after activating the environtment.

Maybe I need to reinsall the pipeline again?

**Comment by leepc12** [comment]
I am sure that `which encode_task_trim_fastq.py` failed inside the pipeline.
I think environment variables like `PATH` were not propagated (`export`ed) into the pipeline.

Are you using bash?
After you activated the env, did you see prefix like `(encode-chip-seq-pipeline)` in your prompt?

**Comment by leonorrib** [comment]
It could be as you say that variables like PATH were not propagated.

Yes, I am using bash.

And yes, after activating the env I see the prefix (encode-chip-seq-pipeline)

**Comment by leepc12** [comment]
Can you try with `source activate encode-chip-seq-pipeline` instead of `conda activate`?

```
$ source /home/lrib/miniconda3/bin/activate encode-chip-seq-pipeline
```

**Comment by leonorrib** [comment]
Ok, I did that and I am running the pipeline again to see whether there is something different now. I will keep you updated.

**Comment by leonorrib** [comment]
It stopped with errors again, unfortunately. I send the log file again in case it helps.
[log.bad4.mod.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/4389012/log.bad4.mod.txt)

**Comment by leepc12** [comment]
I think something is wrong with your Conda/bash configuration? That error means that `which encode_task_...` failed.

Can you make a toy bash script and check if the above which command works in it?
```
$ conda activate encode-chip-seq-pipeline
$ bash run_toy.sh
```

Make sure that your env variables (like PATH) propagate into any shells derived from your current shell where you activated the environment.

If Conda method doesn't work, please switch to Singularity or Docker.

**Comment by leonorrib** [comment]
So, after activating the conda environment the toy script works fine. I have also tried to check the value of the $PATH variable and it's fine. At least it get a relevant one "/home/lrib/miniconda3/envs/encode-chip-seq-pipeline/bin".

**Comment by leepc12** [comment]
Can you check if the following command lines work?
```
leepc12@kadru:~$ source activate encode-chip-seq-pipeline
(encode-chip-seq-pipeline) leepc12@kadru:~$ which encode_task_bowtie2.py
/users/leepc12/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_bowtie2.py
(encode-chip-seq-pipeline) leepc12@kadru:~$ which encode_task_post_align.py
/users/leepc12/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_post_align.py
(encode-chip-seq-pipeline) leepc12@kadru:~$ which encode_task_trimmomatic.py
/users/leepc12/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_trimmomatic.py
```

**Comment by leonorrib** [comment]
I runned this and it works:

lrib@server:~/data/tmp5$ source /home/lrib/miniconda3/bin/activate encode-chip-seq-pipeline
(encode-chip-seq-pipeline) lrib@server:~/data/tmp5$ which encode_task_bowtie2.py
/home/lrib/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_bowtie2.py
(encode-chip-seq-pipeline) lrib@server:~/data/tmp5$ which encode_task_post_align.py
/home/lrib/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_post_align.py
(encode-chip-seq-pipeline) lrib@server:~/data/tmp5$ which encode_task_trimmomatic.py
/home/lrib/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_trimmomatic.py


Running only "source activate encode-chip-seq-pipeline" didn't work. See here:

lrib@server:~/data/tmp5$ source activate encode-chip-seq-pipeline
bash: activate: No such file or directory

**Comment by leepc12** [comment]
Try with `source /home/lrib/miniconda3/bin/activate encode-chip-seq-pipeline` instead of `source activate encode-chip-seq-pipeline`.

**Comment by leonorrib** [comment]
Yes, I did that and it works. I put it already in the previous message :)

**Comment by leepc12** [comment]
I figured out. In your input JSON, `aligner` should be either `bowtie2` or `bwa`.
```javascript
{
    "chip.aligner" : "macs",
}
```

**Comment by leonorrib** [comment]
Yess, that's the problem. It is running correctly now. Thank you!
