### ISSUE TITLE
Problems running on filesystems that uses softlink

### ISSUE THREAD

**Issue by fangpingmu** [ENCODE-DCC/chip-seq-pipeline2#142]
**Describe the bug**

**OS/Platform**
- OS/Platform: Redhat 7, Slurm cluster, singularity
- Pipeline version: [e.g. v1.5.3.1]
- Caper version: [e.g. v0.6.3]

I'm running on a filesystem (beegfs) that does not allow hardlinks between different directories. This problem has been reported at

https://github.com/ENCODE-DCC/chip-seq-pipeline2/issues/91

Based on the discussion, this problem is resolved. I can run the pipeline using ENCSR356KRQ_subsampled_caper.json as input.

However, when I changed to ENCSR000DYI sample, the pipeline failed at merge_fastq step. 

It states that '/bgfs/sam/fangping/encode_chipseq/ENCSR000DYI/chip/1a32d36f-91a2-44d1-9514-561f1b990615/call-align/shard-0/inputs/522247075/rep1.fastq.gz': No such file or directory. This file exists, and it is a soft link.

chip.align RetryableFailure. SHARD_IDX=0, RC=1, JOB_ID=686860, RUN_START=2020-03-31T20:29:37.150Z, RUN_END=2020-03-31T20:34:39.852Z, STDOUT=/bgfs/sam/fangping/encode_chipseq/ENCSR000DYI/chip/1a32d36f-91a2-44d1-9514-561f1b990615/call-align/shard-0/execution/stdout, STDERR=/bgfs/sam/fangping/encode_chipseq/ENCSR000DYI/chip/1a32d36f-91a2-44d1-9514-561f1b990615/call-align/shard-0/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/software/chip-seq-pipeline/src/encode_task_merge_fastq.py", line 104, in <module>
    main()
  File "/software/chip-seq-pipeline/src/encode_task_merge_fastq.py", line 92, in main
    merge_fastqs(fastqs_R1, 'R1', args.out_dir)
  File "/software/chip-seq-pipeline/src/encode_task_merge_fastq.py", line 72, in merge_fastqs
    return copy_f_to_f(fastqs[0], merged)
  File "/software/chip-seq-pipeline/src/encode_lib_common.py", line 265, in copy_f_to_f
    run_shell_cmd(cmd)
  File "/software/chip-seq-pipeline/src/encode_lib_common.py", line 319, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=9099, PGID=9099, RC=1
STDERR=cp: cannot stat '/bgfs/sam/fangping/encode_chipseq/ENCSR000DYI/chip/1a32d36f-91a2-44d1-9514-561f1b990615/call-align/shard-0/inputs/522247075/rep1.fastq.gz': No such file or directory
STDOUT=

[fangping@login0b 522247075]$ ls -l
total 1
lrwxr-xr-x 1 fangping sam 59 Mar 31 16:29 rep1.fastq.gz -> /bgfs/sam/fangping/encode_chipseq/ENCSR000DYI/rep1.fastq.gz

I have tried version 1.3.6. Similar errors appear at the same step.

**Comment by leepc12** [comment]
Upgrade Caper to 0.7.0 or >=0.8.0. These Caper versions have a parameter `--soft-glob-output` which changes cromwell's behavior of globbing outputs (hard-linking -> soft-linking).

`caper run .. --soft-glob-output` or have `soft-glob-output=True` in your Caper conf.

Check if all files in ENCSR000DYI input JSON are valid. What is a full file name of that input JSON and can you upload that file here?

**Comment by fangpingmu** [comment]
The same errors appear after I upgrade to caper 0.7.0. I debugged the problems, and the root causes should be a combination of soft link and singularity.

STDERR=gzip: /bgfs/sam/fangping/encode_chipseq/ENCSR000DYI/chip/1eb470db-5dc8-4ab4-a6ea-cfe1ddea2a8a/call-align/shard-0/inputs/522247075/rep1.fastq.gz: No such file or directory

This file is a soft link.

[fangping@login0b ENCSR000DYI]$ cd /bgfs/sam/fangping/encode_chipseq/ENCSR000DYI/chip/1eb470db-5dc8-4ab4-a6ea-cfe1ddea2a8a/call-align/shard-0/inputs/522247075/
[fangping@login0b 522247075]$ ls -l
total 1
lrwxr-xr-x 1 fangping sam 59 Mar 31 21:26 rep1.fastq.gz -> /bgfs/sam/fangping/encode_chipseq/ENCSR000DYI/rep1.fastq.gz

  File "/software/chip-seq-pipeline/src/encode_task_merge_fastq.py", line 72, in merge_fastqs
    run_shell_cmd(cmd)

    cmd = 'zcat -f {} | gzip -nc > {}'.format(
        ' '.join(fastqs),
        merged)
    run_shell_cmd(cmd)

[fangping@login0a execution]$ singularity exec --cleanenv --home /bgfs/sam/fangping/encode_chipseq/ENCSR000DYI/chip/1eb470db-5dc8-4ab4-a6ea-cfe1ddea2a8a/call-align/shard-0 /ihome/crc/install/encode-dcc/chip-seq-pipeline2-v1.3.6.img zcat -f /bgfs/sam/fangping/encode_chipseq/ENCSR000DYI/chip/1eb470db-5dc8-4ab4-a6ea-cfe1ddea2a8a/call-align/shard-0/inputs/522247075/rep1.fastq.gz | gzip -nc > R1/rep1.fastq.gz
gzip: /bgfs/sam/fangping/encode_chipseq/ENCSR000DYI/chip/1eb470db-5dc8-4ab4-a6ea-cfe1ddea2a8a/call-align/shard-0/inputs/522247075/rep1.fastq.gz: No such file or directory

[fangping@login0a execution]$ singularity exec --cleanenv -B /bgfs/sam/fangping/encode_chipseq/ENCSR000DYI/ /ihome/crc/install/encode-dcc/chip-seq-pipeline2-v1.3.6.img zcat -f /bgfs/sam/fangping/encode_chipseq/ENCSR000DYI/chip/1eb470db-5dc8-4ab4-a6ea-cfe1ddea2a8a/call-align/shard-0/inputs/522247075/rep1.fastq.gz | gzip -nc > R1/rep1.fastq.gz

Note the --home points to the shard-0 directory, while the file of the soft link is not under this directory. The original file is not with the singularity bind path. If I explicitly add the bind path, it works.

I will change to conda env.

**Comment by leepc12** [comment]
Caper has algorithm to find BINDPATH (`-B`) for Singularity. I think it didn't follow symlinks in your input JSON. I will fix this in the next release of Caper.
https://github.com/ENCODE-DCC/caper/blob/master/caper/caper.py#L1160

Until then, can you use absolute real (not soft linked) paths in your input JSON?

**Comment by fangpingmu** [comment]
Absolute path works.
