### ISSUE TITLE
Chip.wdl has a limitation of 6 replicates 

### ISSUE THREAD

**Issue by GFrosi** [ENCODE-DCC/chip-seq-pipeline2#160]
Hi,

I am trying to run the ENCODE pipeline for 12 traits samples and 20 controls on HPC. The pipeline worked (I am using the piperunner.sh code and slurm-singularity as backend from IHEC /
integrative_analysis_chip), however I just have the outputs for 6 replicates (the 6 first described in the Input.json). I checked the chip.wdl file and in fact the pipeline has a "restriction" of 6 replicates:

fastqs
    Array[File] fastqs_rep1_R1 = [] # [merge_id]
    Array[File] fastqs_rep1_R2 = [] # do not define _R2 array if your sample is not paired end
    Array[File] fastqs_rep2_R1 = [] # do not define if you have a single replicate
    Array[File] fastqs_rep2_R2 = [] # do not define _R2 array if your sample is not paired end
    Array[File] fastqs_rep3_R1 = [] # do not define if you have <=2 replicates
    Array[File] fastqs_rep3_R2 = [] # do not define _R2 array if your sample is not paired end
    Array[File] fastqs_rep4_R1 = [] # do not define if you have <=3 replicates
    Array[File] fastqs_rep4_R2 = [] # do not define _R2 array if your sample is not paired end
    Array[File] fastqs_rep5_R1 = [] # do not define if you have <=4 replicates
    Array[File] fastqs_rep5_R2 = [] # do not define _R2 array if your sample is not paired end
    Array[File] fastqs_rep6_R1 = [] # do not define if you have <=5 replicates
    Array[File] fastqs_rep6_R2 = [] # do not define _R2 array if your sample is not paired end
    Array[File] ctl_fastqs_rep1_R1 = []     # [merge_id]
    Array[File] ctl_fastqs_rep1_R2 = [] # do not define _R2 array if your sample is not paired end
    Array[File] ctl_fastqs_rep2_R1 = [] # do not define if you have a single control
    Array[File] ctl_fastqs_rep2_R2 = []   # do not define _R2 array if your sample is not paired end
    Array[File] ctl_fastqs_rep3_R1 = [] # do not define if you have <=2 controls
    Array[File] ctl_fastqs_rep3_R2 = []   # do not define _R2 array if your sample is not paired end
    Array[File] ctl_fastqs_rep4_R1 = [] # do not define if you have <=3 controls
    Array[File] ctl_fastqs_rep4_R2 = []   # do not define _R2 array if your sample is not paired end
    Array[File] ctl_fastqs_rep5_R1 = [] # do not define if you have <=4 controls
    Array[File] ctl_fastqs_rep5_R2 = []   # do not define _R2 array if your sample is not paired end
    Array[File] ctl_fastqs_rep6_R1 = [] # do not define if you have <=5 controls
    Array[File] ctl_fastqs_rep6_R2 = []   # do not define _R2 array if your sample is not paired end

Is there any solution to run more than 6 replicates?

Thanks in advance for your help,
Gabriella Frosi

**Comment by leepc12** [comment]
Please use the latest pipeline which supports up to 10 replicates.

**Comment by GFrosi** [comment]
Hi @leepc12 
Thanks for your answer, 
Unfortunately I have an arbitrary number of replicates (often more than 10).

Is there a way to use the pipeline with more than 10 (indeed any number of replicates)?  

Thanks

**Comment by leepc12** [comment]
No.
If those replicate have any concordance then run a separate pipeline for each replicate. i.e. rep1 only.

**Comment by GFrosi** [comment]
Hi @leepc12, 
Thanks a lot.
