### ISSUE TITLE
Deactivated link. 

### ISSUE THREAD

**Issue by abearab** [ENCODE-DCC/chip-seq-pipeline2#161]
[This page where you said](https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/master/docs/build_genome_database.md#how-to-build-genome-database-for-your-own-genome)
> Get a URL for a gzipped blacklist BED file for your genome. If you don't have one then skip this step. An example blacklist for hg38 is here.

the link is not working.

**Comment by leepc12** [comment]
It's here. https://storage.googleapis.com/encode-pipeline-genome-data/hg38/hg38.blacklist.bed.gz

**Comment by akundaje** [comment]
@leepc12 is this updated to the latest blacklist

**Comment by leepc12** [comment]
@akundaje: No, it's an old one.
New blacklist is here.
https://www.encodeproject.org/files/ENCFF356LFX/@@download/ENCFF356LFX.bed.gz

**Comment by akundaje** [comment]
Ok. We should update the default pipeline blacklist for GRCh38 to the
latest one

**Comment by leepc12** [comment]
Sure, will update ref genome TSV files with accessioned files (including the latest blacklist uploaded to the portal) only in the next release.

**Comment by leepc12** [comment]
Fixed in the latest release. Closing this.
