### ISSUE TITLE
Issue with install_conda_env.sh

### ISSUE THREAD

**Issue by mhayes8520** [ENCODE-DCC/chip-seq-pipeline2#162]
**Describe the bug**
I'm trying to install the conda environment on Stanford Sherlock following the steps here (https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/e2a698d0dcc3d7b16ac8b9dc86d2f9097a35f0b8/docs/install_conda.md), and the script keeps failing at line 15 for some reason. I've followed the previous instructions correctly I think, so I'm not sure what to do. I have copied the error log below

**OS/Platform**
- OS/Platform: Stanford Sherlock
- Conda version: Conda 4.8.2
- Pipeline version: latest
- Caper version: [e.g. v0.6.0]

**Caper configuration file**
Paste contents of `~/.caper/default.conf`.

**Input JSON file**
Paste contents of your input JSON file.

**Error log**
conda 4.8.2
=== Installing pipeline's Conda environments ===
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | chip-seq-pipeline2/scripts/install_conda_env.sh: line 15: 60721 Killed                  conda create -n ${CONDA_ENV_PY3} --file ${REQ_TXT_PY3} -y -c defaults -c r -c bioconda -c conda-forge
```
$ caper debug [WORKFLOW_ID_OR_METADATA_JSON_FILE]
```

**Comment by leepc12** [comment]
```
60721 Killed conda
```
Your job was killed by the cluster. Please do it on a compute node. To log-in on a compute node, use `sbatch` or Sherlock's special command `sdev`. Check `sdev -h` for details.
```
$ sdev -t SOME_LONG_TIME
```

**Comment by mhayes8520** [comment]
Gotcha, I'll try that. Thanks!
