### ISSUE TITLE
Issue with build_genome_data.sh

### ISSUE THREAD

**Issue by mhayes8520** [ENCODE-DCC/chip-seq-pipeline2#163]
**Describe the bug**
I'm stuck trying to build the genome data for sacCer3 since it's not supported already. The build_genome_data.sh script seems to be stuck here:

Entering Ebwt loop

and I think it is specifically stuck trying to build the .bt2 files of the bowtie2 index since they are not yet completed and haven't increased in file size in a long while. I'd say it's been stuck here for about and hour or so. Any ideas?

I also made sure to update the build_genome_data.sh script with the appropriate inputs (genome, chrM, and url to fa.gz file for saccer3)

Finally this was being run in an sdev node in sherlock with 8GB of memory and 2 hours of time

**OS/Platform**
- OS/Platform: Sherlock
- Conda version: 4.8.2
- Pipeline version: latest
- Caper version: [e.g. v0.6.0]

**Caper configuration file**
Paste contents of `~/.caper/default.conf`.

**Input JSON file**
Paste contents of your input JSON file.

**Error log**
Using parameters --bmax 1139729 --dcv 1024
  Doing ahead-of-time memory usage test
  Passed!  Constructing with these parameters: --bmax 1139729 --dcv 1024
Constructing suffix-array element generator
Building DifferenceCoverSample
  Building sPrime
  Building sPrimeOrder
  V-Sorting samples
  V-Sorting samples time: 00:00:01
  Allocating rank array
  Ranking v-sort output
  Ranking v-sort output time: 00:00:00
  Invoking Larsson-Sadakane on ranks
  Invoking Larsson-Sadakane on ranks time: 00:00:00
  Sanity-checking and returning
Building samples
Reserving space for 22 sample suffixes
Generating random suffixes
QSorting 22 sample offsets, eliminating duplicates
QSorting sample offsets, eliminating duplicates time: 00:00:00
Multikey QSorting 22 samples
  (Using difference cover)
  Multikey QSorting samples time: 00:00:00
Calculating bucket sizes
Splitting and merging
  Splitting and merging time: 00:00:00
Split 3, merged 9; iterating...
Splitting and merging
  Splitting and merging time: 00:00:00
Split 2, merged 3; iterating...
Splitting and merging
  Splitting and merging time: 00:00:00
Avg bucket size: 810473 (target: 1139728)
Converting suffix-array elements to index image
Allocating ftab, absorbFtab
Entering Ebwt loop

**Comment by leepc12** [comment]
Please upload your shell script here. I will test it on my cluster.

**Comment by leepc12** [comment]
Closing this.
