### ISSUE TITLE
error with install_conda_env.sh

### ISSUE THREAD

**Issue by ychsiao1** [ENCODE-DCC/chip-seq-pipeline2#165]
Describe the bug
I'm essentially getting the same error as #162, except i'm on ubuntu 18:04. How should I fix this? It used to work fine before.

OS/Platform

OS/Platform: Ubuntu:18.04
Conda version: Conda 4.7.12
Pipeline version: latest
Caper version: [e.g. v0.6.0]
Caper configuration file
Paste contents of ~/.caper/default.conf.

Input JSON file
Paste contents of your input JSON file.

Error log
conda 4.7.12
=== Installing pipeline's Conda environments ===
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done

**Comment by leepc12** [comment]
Doesn't look like the same error as #162 .
I think it's just taking long to resolve dependency conflicts?
Please attach a full error log.

**Comment by ychsiao1** [comment]
conda 4.7.12
=== Installing pipeline's Conda environments ===
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... install_conda_env.sh: line 15:  4996 Killed                  conda create -n ${CONDA_ENV_PY3} --file ${REQ_TXT_PY3} -y -c defaults -c r -c bioconda -c conda-forge


This is the error message I'm getting while trying to build on a Docker image

**Comment by leepc12** [comment]
```
4996 Killed conda create -n ....
```

Your cluster killed it. Please run it on a compute node.

**Comment by ychsiao1** [comment]
can you point me to how to do this on linux. Thanks
