### ISSUE TITLE
pipeline gets stuck at filtering step

### ISSUE THREAD

**Issue by mhayes8520** [ENCODE-DCC/chip-seq-pipeline2#166]
**Describe the bug**
The pipeline doesn't seem to be running to completion in sherlock using the command you've given here: https://github.com/ENCODE-DCC/caper. It stops at the call-filter step with the stderr.submit file saying: "sbatch: error: Batch job submission failed: Requested node configuration is not available". Attached are the command I ran, the slurm.out, and the stderr.submit files.
[caper_debug_error.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/4806559/caper_debug_error.txt)

[sbatch_command.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/4806551/sbatch_command.txt)
[slurm-2558098.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/4806552/slurm-2558098.txt)
[stderr.submit.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/4806553/stderr.submit.txt)

**OS/Platform**
- OS/Platform: Sherlock
- Conda version: Conda 4.8.2
- Pipeline version: latest
- Caper version: [e.g. v0.6.0]

**Caper configuration file**
backend=slurm
slurm-partition=normal

# DO NOT use /tmp here
# You can use $OAK or $SCRATCH storages here.
# Caper stores all important temp files and cached big data files here
# If not defined, Caper will make .caper_tmp/ on your local output directory
# which is defined by out-dir, --out-dir or $CWD
# Use a local absolute path here
tmp-dir=/scratch/users/mihayes

# IMPORTANT warning for Stanford Sherlock cluster
# ====================================================================
# DO NOT install any codes/executables
# (java, conda, python, caper, pipeline's WDL, pipeline's Conda env, ...) on $SCRATCH or $OAK.
# You will see Segmentation Fault errors.
# Install all executables on $HOME or $PI_HOME instead.
# It's STILL OKAY to read input data from and write outputs to $SCRATCH or $OAK.
# ====================================================================

cromwell=/home/users/mihayes/.caper/cromwell_jar/cromwell-47.jar
womtool=/home/users/mihayes/.caper/womtool_jar/womtool-47.jar

**Input JSON file**
{
    "chip.title" : "Pho4_ChIP_NoPi",
    "chip.description" : "Zhou and O'Shea 2011 Pho4 ChIP-seq",

    "chip.pipeline_type" : "tf",
    "chip.aligner" : "bowtie2",
    "chip.align_only" : false,
    "chip.true_rep_only" : false,

    "chip.genome_tsv" : "/oak/stanford/groups/pfordyce/data-workspace/repeats/genomes/saccer3/encode_chip_pipeline_genome/saccer3_flab.tsv",

    "chip.paired_end" : false,
    "chip.ctl_paired_end" : false,

    "chip.always_use_pooled_ctl" : false,

    "chip.fastqs_rep1_R1" : [ "/oak/stanford/groups/pfordyce/data-workspace/repeats/data/raw/Zhou_OShea_2011/Pho4_ChIP_NoPi_R1.fastq.gz" ],
    "chip.fastqs_rep2_R1" : [ "/oak/stanford/groups/pfordyce/data-workspace/repeats/data/raw/Zhou_OShea_2011/Pho4_ChIP_NoPi_R2.fastq.gz" ],

    "chip.ctl_fastqs_rep1_R1" : [ "/oak/stanford/groups/pfordyce/data-workspace/repeats/data/raw/Zhou_OShea_2011/Pho4_Input_NoPi.fastq.gz" ],
    "chip.ctl_fastqs_rep2_R1" : [ "/oak/stanford/groups/pfordyce/data-workspace/repeats/data/raw/Zhou_OShea_2011/Pho2_Input_NoPi.fastq.gz" ],
    "chip.ctl_fastqs_rep3_R1" : [ "/oak/stanford/groups/pfordyce/data-workspace/repeats/data/raw/Zhou_OShea_2011/Cbf1_Input_NoPi.fastq.gz" ],

    "chip.always_use_pooled_ctl" : true,
    "chip.ctl_depth_ratio" : 1.2,

    "chip.mapq_thresh" : 255,
    "chip.dup_marker" : "picard",
    "chip.no_dup_removal" : false,

    "chip.peak_caller" : "spp",
    "chip.cap_num_peak_macs2" : 500000,
    "chip.pval_thresh" : 0.01,
    "chip.fdr_thresh" : 0.01,
    "chip.idr_thresh" : 0.05,
    "chip.cap_num_peak_spp" : 300000,

    "chip.enable_jsd" : true,
    "chip.enable_gc_bias" : true,
    "chip.enable_count_signal_track" : true
}

**Error log**
Caper automatically runs a troubleshooter for failed workflows. If it doesn't then get a `WORKFLOW_ID` of your failed workflow with `caper list` or directly use a `metadata.json` file on Caper's output directory.
```
$ caper debug [WORKFLOW_ID_OR_METADATA_JSON_FILE]
```
caper debug metadata.json didn't work and threw an error in the txt file attached.

**Comment by leepc12** [comment]
Check if your partition (`normal`?)'s limit for cpu, memory and walltime.

Reduce resources defined in resource parameters in your input JSON for filter task (`chip.filter_*`).
e.g. try with lower `chip.filter_mem_mb` and `chip.filter_time_hr`.

**Comment by mhayes8520** [comment]
I believe it does limit those to some extent, however I'm confused if that's the problem because the defaults settings for alignment draw on more cores than the filtering does. 

In any case, I added the following 3 lines to my .json file:
    "chip.filter_cpu" : 1,
    "chip.filter_mem_mb" : 10000,
    "chip.filter_time_hr" : 4
and unfortunately, I got the same error with the stderr.submit file saying: sbatch: error: "Batch job submission failed: Requested node configuration is not available". 

What are the minimum requirements for the filtering step?

**Comment by leepc12** [comment]
Check if `normal` partition allows that resource configuration.
Try to `sbatch` `hello world` problem with cpu=1, mem=10G, time=4h, something like
```
sbatch -p normal -t=4H_TO_MINUTE? --mem=10G  --wrap "echo hello world"
```
and see if that works.

**Comment by mhayes8520** [comment]
The command you sent works ("hello world" is in the slurm.out), so those setting should work with sbatch generally speaking.

**Comment by leepc12** [comment]
I will test it and let u know.

**Comment by mhayes8520** [comment]
Hi Jin,

I recently got access to the kundaje lab sherlock cluster (I changed the partition in the .caper/default_conf file to akundaje), and the previous error went away, though I'm now getting a different error during the filtering process in which a run_shell_cmd throws an error. The error in the slurm.out is as follows: "Job chip.filter_R1:1:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details", however I don't know where this continueOnReturnCode is located. Attached are the slurm.out, stdout, and stderr. 
[slurm-3024011.out.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/4839523/slurm-3024011.out.txt)
[stderr.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/4839524/stderr.txt)
[stdout.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/4839525/stdout.txt)

Any help would be appreciated!

**Comment by mhayes8520** [comment]
Ultimately the problem was that I had the mapq threshold set to 255, which you say is the default for bowtie2 in the json file explanation page. However, this caused everything to be filtered out and is incorrect. Please change https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/master/docs/input.md to reflect the correct defaults.

**Comment by akundaje** [comment]
Jin - please correct this and also check the documentation parameters
carefully so that it reflects the latest.

Anshul
