### ISSUE TITLE
Gecode version?

### ISSUE THREAD

**Issue by dzhaobio** [ENCODE-DCC/chip-seq-pipeline2#179]
https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/master/scripts/download_genome_data.sh#L79
TSS="https://storage.googleapis.com/encode-pipeline-genome-data/hg38/ataqc/hg38_gencode_tss_unique.bed.gz"

https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/master/scripts/download_genome_data.sh#L116
TSS="https://storage.googleapis.com/encode-pipeline-genome-data/mm10/ataqc/mm10_gencode_tss_unique.bed.gz"

I will analyze RNAseq and ChIPseq together. I prefer to use the same version of GTF file for RNAseq and ChIPseq. The TSS info was derived from the GNCODE GTF. Which versions were used for hg38 and mm10? Thank you!

**Comment by leepc12** [comment]
Those TSS are for `v1` genome TSV. If you scroll further down in the shell script you will be able to find these.

hg38: https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/master/scripts/download_genome_data.sh#L99
> https://www.encodeproject.org/files/ENCFF493CCB

mm10: https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/master/scripts/download_genome_data.sh#L135
> https://www.encodeproject.org/files/ENCFF498BEJ

**Comment by dzhaobio** [comment]
I see. Thank you!

**Comment by dzhaobio** [comment]
I find the default version I downloaded is "v1"  (I learned that from the scripts/download_genome_data.sh file. I installed the pipeline a few months ago).

Do you remember which version of Gencode annotation was used for "v1" (hg38 and mm10)?

Or, Can I download the "v3" genomes and use it without reinstalling the pipeline?

Thank you!

**Comment by leepc12** [comment]
You don't have to reinstall either pipeline or Conda environment. Just use `v3` genome TSV.
`v1` is generated from v24 (hg38) and vM7 (mm10).

**Comment by dzhaobio** [comment]
Got it! Thank you!
