### ISSUE TITLE
Analysis of broad marks

### ISSUE THREAD

**Issue by emattei** [ENCODE-DCC/chip-seq-pipeline2#193]
Hi,
Is there a way to specify that the input histone mark is a broad mark and therefore get the broad peaks and gapped peaks bed files?

**Comment by akundaje** [comment]
The pipeline currently does not support broad/gapped peak calling due to
instability in the peak callers for these outputs. You can take the
alignment file outputs from the pipeline and run them through any broad
peak callers if you like.

**Comment by emattei** [comment]
Thank you for the clarification!
