### ISSUE TITLE
Conda env installation on a custom folder

### ISSUE THREAD

**Issue by Fnyasimi** [ENCODE-DCC/chip-seq-pipeline2#196]
I am setting up a pipeline on a cluster but I have a challenge installing the environment on a custom path which is visible to all nodes on the hpc.
 
The reason I am doing this is because the environments in the base conda directory are not visible to all the nodes hence the need to install on a custom path which is visible to all computing nodes.

I have tried using `--prefix` but I didn't manage to set up the pipeline configurations.

Kindly help me set up tweak the installation scripts to set up the environments in a custom path and do all the necessary configurations.

Ps: I don't have sudo rights to the cluster

**Comment by Fnyasimi** [comment]
@leepc12  I would specifically to sept up the tool versions for the `v1.4.0.1 pipeline version` because all my json files are configured for that version and I have already analyzed  half of the work using that version. I would like to maintain the consistence

**Comment by leepc12** [comment]
Install `miniconda3` on the path visible to all nodes and remove all other condas from your `PATH`.

**Comment by Fnyasimi** [comment]
Thanks for the update
