### ISSUE TITLE
split into subworkflows

### ISSUE THREAD

**Issue by antonkulaga** [ENCODE-DCC/chip-seq-pipeline2#20]
As you try to make it work with any input time possible the chip.wdl is a big mess and hard to deal with, I suggest that you make chip.wdl as a wrapper that deals with different types of intputs and then redirects execution to proper subworkflows depending on input types.

**Comment by leepc12** [comment]
Thanks for your suggestion but there are several reasons why we chose that way. Sub-workflow does not actually work as expected with cromwell. Sub-workflow WDL file must exist on a working directory where users run pipeline (not on the git source directory). Imported sub-workflow WDL file can be accessed via internet (with `http://`) though. But this makes it a bit hard to maintain/version-control our pipeline.
