### ISSUE TITLE
MACS2 Peaks Cap

### ISSUE THREAD

**Issue by YogiOnBioinformatics** [ENCODE-DCC/chip-seq-pipeline2#202]
I had a question about the number of peaks taken from `MACS2`. 
Why is the number of peaks capped at 500,000 for this pipeline vs 300,000 for the `ENCODE-DCC ATAC-Seq Pipeline`?

It would be very useful for me to know since I plan to analyze ChIP-Seq and ATAC-Seq data from the same biological samples soon. 
Please let me know if this makes sense.

**Comment by akundaje** [comment]
No particular reason other than that certain types of histone marks (ChIP)
can often have a larger number of narrow peaks than ATAC/DNase.

-Anshul.

**Comment by YogiOnBioinformatics** [comment]
Perfect! :) 
Thanks so much as always for the quick reply.
