### ISSUE TITLE
Example Chip-seq JSON not working

### ISSUE THREAD

**Issue by grevetjd** [ENCODE-DCC/chip-seq-pipeline2#240]
## Describe the bug
I'm trying to set up the Encode CHIP-seq pipeline and have it run on my computer, but running into issues with the following errors coming up: "Bad output 'align_ctl.bai': Bad array access glob(\"*.bai\")[0]: Array size 0 does not have an index value '0'" as listed below, I've tried a number of things like using a more recent version of cromwell/womtools (v70). My directory doesn't have issues with soft-linking. It seems like the issue is specifically with indexing the bam files, the default from the workflow is to use samtools 1.9 and there are more recent versions like 1.13 not sure if that is contributing.  Of note I did have to downgrade the tbb library to 2020.2 version, the workflow wasn't able to find it. 

## OS/Platform
- OS/Platform: MacOS 11.6
- Conda version: 4.10.3.
- Pipeline version: 1.0
- Caper version: 1.6.3

## Caper configuration file
backend=local

Hashing strategy for call-caching (3 choices)
This parameter is for local (local/slurm/sge/pbs) backend only.
This is important for call-caching,
which means re-using outputs from previous/failed workflows.
Cache will miss if different strategy is used.
"file" method has been default for all old versions of Caper<1.0.
"path+modtime" is a new default for Caper>=1.0,
file: use md5sum hash (slow).
path: use path.
path+modtime: use path and modification time.
local-hash-strat=path+modtime

Local directory for localized files and Cromwell's intermediate files
If not defined, Caper will make .caper_tmp/ on local-out-dir or CWD.
/tmp is not recommended here since Caper store all localized data files
on this directory (e.g. input FASTQs defined as URLs in input JSON).
local-loc-dir=

cromwell=/Users/grevetjd/.caper/cromwell_jar/cromwell-59.jar
womtool=/Users/grevetjd/.caper/womtool_jar/womtool-59.jar

## Input JSON file
https://storage.googleapis.com/encode-pipeline-test-samples/encode-chip-seq-pipeline/ENCSR000DYI_subsampled_chr19_only.json

## Troubleshooting result

[
    {
        "message": "Workflow failed",
        "causedBy": [
            {
                "message": "Failed to evaluate job outputs",
                "causedBy": [
                    {
                        "causedBy": [],
                        "message": "Bad output 'align.bai': Bad array access glob(\"*.bai\")[0]: Array size 0 does not have an index value '0'"
                    }
                ]
            },
            {
                "message": "Failed to evaluate job outputs",
                "causedBy": [
                    {
                        "message": "Bad output 'align_R1.bai': Bad array access glob(\"*.bai\")[0]: Array size 0 does not have an index value '0'",
                        "causedBy": []
                    }
                ]
            },
            {
                "message": "Failed to evaluate job outputs",
                "causedBy": [
                    {
                        "message": "Bad output 'align_ctl.bai': Bad array access glob(\"*.bai\")[0]: Array size 0 does not have an index value '0'",
                        "causedBy": []
                    }
                ]
            },
            {
                "message": "Failed to evaluate job outputs",
                "causedBy": [
                    {
                        "message": "Bad output 'align_R1.bai': Bad array access glob(\"*.bai\")[0]: Array size 0 does not have an index value '0'",
                        "causedBy": []
                    }
                ]
            },
            {
                "message": "Failed to evaluate job outputs",
                "causedBy": [
                    {
                        "message": "Bad output 'align.bai': Bad array access glob(\"*.bai\")[0]: Array size 0 does not have an index value '0'",
                        "causedBy": []
                    }
                ]
            },
            {
                "causedBy": [
                    {
                        "causedBy": [],
                        "message": "Bad output 'align_ctl.bai': Bad array access glob(\"*.bai\")[0]: Array size 0 does not have an index value '0'"
                    }
                ],
                "message": "Failed to evaluate job outputs"
            }
        ]
    }
]

**Comment by leepc12** [comment]
I see. I am closing this. Please feel free to reopen it if you need more help
