### ISSUE TITLE
An error occurs when running the process with test data

### ISSUE THREAD

**Issue by tyewaichung** [ENCODE-DCC/chip-seq-pipeline2#253]
Hello
When I used the encode chip-seq pipeline test data set to run the process today, the following error occurred and I don't know how to solve it.

2021-12-09 21:09:27,028|caper.cromwell_workflow_monitor|INFO| Workflow: id=8414c8ac-ac89-4579-95d0-9c6ae64b2fcb, status=Failed
2021-12-09 21:10:03,614|caper.cromwell_metadata|INFO| Wrote metadata file. /home/zhong/chip-seq-pipeline2-2.1.2/chip/8414c8ac-ac89-4579-95d0-9c6ae64b2fcb/metadata.json
2021-12-09 21:10:03,614|caper.cromwell|INFO| Workflow failed. Auto-troubleshooting...
* Started troubleshooting workflow: id=8414c8ac-ac89-4579-95d0-9c6ae64b2fcb, status=Failed
* Found failures JSON object.
[
    {
        "message": "Workflow failed",
        "causedBy": [
            {
                "message": "Job chip.xcor:1:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.",
                "causedBy": []
            },
            {
                "message": "Job chip.xcor:0:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.",
                "causedBy": []
            }
        ]
    **}
]
* Recursively finding failures in calls (tasks)...

==== NAME=chip.xcor, STATUS=RetryableFailure, PARENT=
SHARD_IDX=0, RC=1, JOB_ID=1142
START=2021-12-09T13:05:43.498Z, END=2021-12-09T13:05:52.396Z
STDOUT=/home/zhong/chip-seq-pipeline2-2.1.2/chip/8414c8ac-ac89-4579-95d0-9c6ae64b2fcb/call-xcor/shard-0/execution/stdout
STDERR=/home/zhong/chip-seq-pipeline2-2.1.2/chip/8414c8ac-ac89-4579-95d0-9c6ae64b2fcb/call-xcor/shard-0/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/home/zhong/miniconda3/envs/encode-chip-seq-pipeline-spp/bin/encode_task_xcor.py", line 156, in <module>
    main()
  File "/home/zhong/miniconda3/envs/encode-chip-seq-pipeline-spp/bin/encode_task_xcor.py", line 144, in main
    args.chip_seq_type, args.exclusion_range_min, args.exclusion_range_max)
  File "/home/zhong/miniconda3/envs/encode-chip-seq-pipeline-spp/bin/encode_task_xcor.py", line 105, in xcor
    run_shell_cmd(cmd1)
  File "/home/zhong/miniconda**

How can I solve this kind of problem?
Is it to delete the original conda environment and reinstall it?
But after trying it, I found that it did not solve the problem

**Comment by leepc12** [comment]
Did you try with the latest pipeline + caper (both released on 12/8/2021)?

**Comment by tyewaichung** [comment]
Yes, I use the latest version of pipline and caper, but I found a problem. It may be that I did not re-init my backend, which caused the software used in the updated version environment to not be updated in time. I will try again now. I don't know if there will be any errors.

**Comment by tyewaichung** [comment]
> Did you try with the latest pipeline + caper (both released on 12/8/2021)?

Yes, I use the latest version of pipline and caper, but I found a problem. It may be that I did not re-init my backend, which caused the software used in the updated version environment to not be updated in time. I will try again now. I don't know if there will be any errors.

**Comment by tyewaichung** [comment]
Through the above attempts, the process has been successfully passed. If there are follow-up bugs that need to be resolved, I am asking you questions
Thank you
