### ISSUE TITLE
Unable to run caper on windows

### ISSUE THREAD

**Issue by silentsilencee** [ENCODE-DCC/chip-seq-pipeline2#258]
hey team:

I have followed the steps mentioned in the README which involves pip3 install caper. When trying to do caper init on a windows 10 machine i get an error saying command not recognized. This is even after resetting my bashrc and tryin the export command mentioned. What can i do to solve this issue?

best

**Comment by leepc12** [comment]
Did you run it on Ubuntu (as Windows sub-system)?

**Comment by silentsilencee** [comment]
Hey @leepc12 i did not run it on ubuntu. Does this only work for Ubuntu?

**Comment by leepc12** [comment]
Yes, it should work on Ubuntu (Windows sub-system). It doesn't run on Windows shell.
Open up Microsoft store app and install Ubuntu.
