### ISSUE TITLE
cc.plot.png, cc.fraglen, no such file or directory

### ISSUE THREAD

**Issue by shirleytemples** [ENCODE-DCC/chip-seq-pipeline2#259]
When I run the command 

"caper run chip.wdl -i https://storage.googleapis.com/encode-pipeline-test-samples/encode-chip-seq-pipeline/ENCSR000DYI_subsampled_chr19_only.json --conda", 

it returns that 

"error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
STDOUT=
ln: failed to access '/home/shirleytemples/chip-seq-pipeline2/chip/c38f96bf-ffcf-4f31-b063-3f901c0137ad/call-xcor/shard-1/attempt-2/execution/*.cc.plot.png': No such file or directory
ln: failed to access '/home/shirleytemples/chip-seq-pipeline2/chip/c38f96bf-ffcf-4f31-b063-3f901c0137ad/call-xcor/shard-1/attempt-2/execution/*.cc.fraglen.txt': No such file or directory
ln: failed to access '/home/shirleytemples/chip-seq-pipeline2/chip/c38f96bf-ffcf-4f31-b063-3f901c0137ad/call-xcor/shard-1/attempt-2/execution/*.cc.plot.pdf': No such file or directory
ln: failed to access '/home/shirleytemples/chip-seq-pipeline2/chip/c38f96bf-ffcf-4f31-b063-3f901c0137ad/call-xcor/shard-1/attempt-2/execution/*.cc.qc': No such file or directory

2022-01-24 00:55:43,410|caper.nb_subproc_thread|ERROR| Cromwell failed. returncode=1"

I am not too sure how to eliminate this error and get the json file to run.

**Comment by leepc12** [comment]
Did you install pipeline's Conda environment (`scripts/install_conda_env.sh`)?
What is your pipeline and caper versions? Both should be >= 2.0.0.

Please run this for debugging:
```bash
$ source activate encode-chip-seq-pipeline-spp

# find conda env's bin/ and lib/ directory
(encode-chip-seq-pipeline-spp) $ which bedtools
/users/leepc12/miniconda3/envs/encode-chip-seq-pipeline-spp/bin/bedtools

# check if libreadline* exists
(encode-chip-seq-pipeline-spp) $ ls -l /users/leepc12/miniconda3/envs/encode-chip-seq-pipeline-spp/lib/libreadline*
-rw-rw-r-- 7 leepc12 users 568982 Aug 28  2018 /users/leepc12/miniconda3/envs/encode-chip-seq-pipeline-spp/lib/libreadline.a
lrwxrwxrwx 1 leepc12 users     18 Dec  7 13:11 /users/leepc12/miniconda3/envs/encode-chip-seq-pipeline-spp/lib/libreadline.so -> libreadline.so.7.0
lrwxrwxrwx 1 leepc12 users     18 Dec  7 13:11 /users/leepc12/miniconda3/envs/encode-chip-seq-pipeline-spp/lib/libreadline.so.7 -> libreadline.so.7.0
-rwxrwxr-x 7 leepc12 users 372072 Aug 28  2018 /users/leepc12/miniconda3/envs/encode-chip-seq-pipeline-spp/lib/libreadline.so.7.0
```

**Comment by shirleytemples** [comment]
Yup, I installed pipeline's Conda environment and my version for conda is 4.10.3 and for caper is 2.1.2.

I ran the debugging steps that you mentioned.

#### find conda env's bin/ and lib/ directory
```
$ source activate encode-chip-seq-pipeline-spp
(encode-chip-seq-pipeline-spp) $ which bedtools
/home/shirleytemples/miniconda3/envs/encode-chip-seq-pipeline-spp/bin/bedtools
```

#### check if libreadline* exists
```
(encode-chip-seq-pipeline-spp) shirleytemples@DESKTOP-9R1GDM5:~/chip-seq-pipeline2$ ls -l /home/shirleytemples/miniconda3/envs/encode-chip-seq-pipeline-spp/lib/libreadline*

-rw-rw-r-- 4 shirleytemples shirleytemples 568982 Aug 28  2018 /home/shirleytemples/miniconda3/envs/encode-chip-seq-pipeline-spp/lib/libreadline.a
lrwxrwxrwx 1 shirleytemples shirleytemples     18 Jan 23 23:44 /home/shirleytemples/miniconda3/envs/encode-chip-seq-pipeline-spp/lib/libreadline.so -> libreadline.so.7.0
lrwxrwxrwx 1 shirleytemples shirleytemples     18 Jan 23 23:44 /home/shirleytemples/miniconda3/envs/encode-chip-seq-pipeline-spp/lib/libreadline.so.7 -> libreadline.so.7.0
-rwxrwxr-x 4 shirleytemples shirleytemples 372072 Aug 28  2018 /home/shirleytemples/miniconda3/envs/encode-chip-seq-pipeline-spp/lib/libreadline.so.7.0
```

####The outputs seem to match what you have. However, when I try again and rerun the command

`caper run chip.wdl -i https://storage.googleapis.com/encode-pipeline-test-samples/encode-chip-seq-pipeline/ENCSR000DYI_subsampled_chr19_only.json --conda`

it returns the same error

```
STDERR=/home/shirleytemples/miniconda3/envs/encode-chip-seq-pipeline-spp/lib/R/bin/exec/R: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
STDOUT=
ln: failed to access '/home/shirleytemples/chip-seq-pipeline2/chip/902d009e-1aa9-45c7-acb9-0fb3a04e6527/call-xcor/shard-1/attempt-2/execution/*.cc.plot.png': No such file or directory
ln: failed to access '/home/shirleytemples/chip-seq-pipeline2/chip/902d009e-1aa9-45c7-acb9-0fb3a04e6527/call-xcor/shard-1/attempt-2/execution/*.cc.fraglen.txt': No such file or directory
ln: failed to access '/home/shirleytemples/chip-seq-pipeline2/chip/902d009e-1aa9-45c7-acb9-0fb3a04e6527/call-xcor/shard-1/attempt-2/execution/*.cc.plot.pdf': No such file or directory
ln: failed to access '/home/shirleytemples/chip-seq-pipeline2/chip/902d009e-1aa9-45c7-acb9-0fb3a04e6527/call-xcor/shard-1/attempt-2/execution/*.cc.qc': No such file or directory


2022-01-24 16:46:26,383|caper.nb_subproc_thread|ERROR| Cromwell failed. returncode=1
2022-01-24 16:46:26,384|caper.cli|ERROR| Check stdout in `/home/shirleytemples/chip-seq-pipeline2/cromwell.out.3
```
Not to sure how to further debug the issue.

**Comment by shirleytemples** [comment]
Just wanted to follow up and see if there are any additional steps I could do, I am still stuck on this. Any help would be much appreciated! @leepc12

**Comment by leepc12** [comment]
This looks like Conda's issue (missing readline 6 for old R versions).
It's currently very hard to resolve conflicts without `conda-forge`.

I will fix this in the next release. Until then please manually install readline 6.0 on your system.
For example (Debian-based OS)
```bash
$ sudo apt-get install libreadline6
```

**Comment by shirleytemples** [comment]
Thanks for your help, it works now. But I had to several other things for it to work as libreadline6 is no longer available. 

```
sudo apt-get install libreadline-dev

cd /lib/x86_64-linux-gnu/

sudo ln -s libreadline.so.8.0 libreadline.so.6

sudo apt-get install libncurses5
```
`
