### ISSUE TITLE
parrallel proccessing with spp

### ISSUE THREAD

**Issue by louisgevirtzman** [ENCODE-DCC/chip-seq-pipeline2#268]
I am confused with this line of code from encode_task_spp.py
nth_param = '-p={}'.format(nth) if nth < 2 else ''
should it be:
nth_param = '-p={}'.format(nth) if nth >= 2 else ''
when I run the pipeline with spp it does not seem to use multiple threads

**Comment by leepc12** [comment]
Thanks for reporting. This will be fixed in the next release.

**Comment by leepc12** [comment]
Fixed in v2.1.5
