### ISSUE TITLE
Can we still run this pipeline with bam file as input?

### ISSUE THREAD

**Issue by mkmwong** [ENCODE-DCC/chip-seq-pipeline2#27]
As title. Thanks!

**Comment by leepc12** [comment]
Sure, define your BAMs in your input JSON.
```
{
    ....
    "bams" :  [ "BAM_REP1.bam", "BAM_REP2.bam" ],
    ....
}
```

**Comment by mkmwong** [comment]
If they were already deduplicated, do I do something like "nodup_bams" and "ctl_nodup_bams" instead of "bams" and "ctl_bams"?

**Comment by leepc12** [comment]
@mkmwong: Yes, exactly.

**Comment by mkmwong** [comment]
thank you so much for your swift response!
