### ISSUE TITLE
Problem about build_genome_data.sh

### ISSUE THREAD

**Issue by Mozillian1** [ENCODE-DCC/chip-seq-pipeline2#279]
I'm trying to use this script to build my own genome data. I found that if I set `REF_FA=somegenome.fa`, this script will remove '.fa' file as a tmp file in line 292~294 and set the corresponding '.gz' file as ref_fa in the final TSV file. But I failed to find lines to compress the original fa file. So when I carry on analyses with the built genome TSV, I will encounter an error that the '.fa.gz' file cannot be found. I suggest adding a line like `gzip -nc ${REF_FA_PREFIX} > ${REF_FA_PREFIX}.gz` after line 212. Thank you for this pipeline.

**Comment by leepc12** [comment]
Thanks for reporting this. I will fix it in the next release.

**Comment by leepc12** [comment]
Sorry about very late reply, didn't have time to work on this issue.
Please gzip the FASTA file before submitting it to the builder so that it has a `.fa.gz` suffix.
