### ISSUE TITLE
call-spp_ppr1 wall time exceeds 48h

### ISSUE THREAD

**Issue by mkmwong** [ENCODE-DCC/chip-seq-pipeline2#28]
Hi,

I'm running the pipeline on the test data on slurm. I encountered the problem that when call-spp_ppr1 script is being submitted, the request wall-time is 72 hours. Can this be lowered somehow? I looked at the input.json and it doesn't look like we could change the wall-time for this particular thing?

**Comment by leepc12** [comment]
Please try with 
```
{
    ...
    "chip.spp_time_hr" : 47,
    ...
}
```
