### ISSUE TITLE
conda list ucsc-twobittofa

### ISSUE THREAD

**Issue by YasaminRaziee** [ENCODE-DCC/chip-seq-pipeline2#308]
hello,
I tried to install `ucsc-twobittofa` in conda environment and all things seems like good but when I type the package name it response the command not found. I can see the name in my conda list and when I  utilize conda list ucsc-twobittofa I can see all information of it .

**Comment by hitz** [comment]
We recommend not using Conda although it's technically supported.   We cannot help you debug your conda installation :(

**Comment by YasaminRaziee** [comment]
I found the package form anaconda repository
