### ISSUE TITLE
Pipeline issue with call-bwa step

### ISSUE THREAD

**Issue by Scubatuba99** [ENCODE-DCC/chip-seq-pipeline2#33]
**Describe the bug**
Whenever I run the pipeline using raw fastq files as the input I get this error:
Exception: bwa index does not exists. Prefix = ~/cromwell-executions/chip/621c36a5-68e0-4ad4-b201-b5c477fb5cfc/call-bwa/shard-0/inputs/1499526/null
ln: failed to access ‘*.bam’: No such file or directory
ln: failed to access ‘*.bai’: No such file or directory
ln: failed to access ‘*.flagstat.qc’: No such file or directory

**OS/Platform and dependencies**
- CentOS 7.5, running SLURM scheduler
- cromwell-34
- Conda 4.5.11

**Attach logs**
[debug_33.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2516884/debug_33.tar.gz)

**Comment by leepc12** [comment]
Pipeline couldn't find BWA index files.

Did you build genome database by running `conda/install_genome_data.sh`? Did you skip it because you already built for atac seq pipeline?

**Comment by Scubatuba99** [comment]
I did skip it for that very reason. Is it okay to pull from the kundalje lab genome data or should I run install_genome_data.sh and have it make my own bwa-index for me?

**Comment by Scubatuba99** [comment]
And just pulling from the kundalje lab library works just fine. Thank you.
