### ISSUE TITLE
Where to find reo1/rep2 signal track?

### ISSUE THREAD

**Issue by mkmwong** [ENCODE-DCC/chip-seq-pipeline2#34]
As topic. is it in call_macs-ppr1/2 or is it in call_macs-pr1/2? Inside all those folder, I can only fine null.fc.signal.bigwig, which is the size of 0.

**Comment by leepc12** [comment]
Signal trackes (bigwigs) are not generated for pseudo replicates (pr) and pooled pseudo replicates (ppr).
