### ISSUE TITLE
problem preventing xcor from running

### ISSUE THREAD

**Issue by Scubatuba99** [ENCODE-DCC/chip-seq-pipeline2#36]
I'm running the pipeline with one replicate and one control and I noticed that even when I include the "disable.xcor" parameter on the .json file it still tries to run it and it fails the run at the xcor step. I don't mind having to do the rest of qc stuff, I just was hoping to finish the pipeline so I won't have to do each step manually (or write my own pipeline/script).  I also have the "true_reps_only" parameter set to true, do they cancel each other out? 

**OS/Platform and dependencies**
- CentOS 7
- Cromwell-34
- conda version 4.5.11

**Attach logs**
[debug_36.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2530539/debug_36.tar.gz)

**Comment by leepc12** [comment]
There is no `disable_xcor` for chip-seq-pipeline. It's only for atac-seq-pipeline.

Did you get any error while installing conda dependencies?
Can you try `conda/uninstall_dependencies.sh` and then `conda/install_dependencies.sh`? 

Can you also try other methods like singularity and docker? You can avoid these annoying conda dependencies errors by using one of them.

**Comment by leepc12** [comment]
Closing this due to long inactivity
