### ISSUE TITLE
Unmatched control

### ISSUE THREAD

**Issue by dcdxy** [ENCODE-DCC/chip-seq-pipeline2#39]
Is there a way to use controls without specifying the pairing? For example, if I have three biological `"chip.fastqs"` replicates and only one control `"chip.ctl_fastqs"` replicate, can I avoid arbitrarily matching the control or must I assign it to one of `"chip.ctl_fastqs_rep1"`, `"chip.ctl_fastqs_rep2"`, or `"chip.ctl_fastqs_rep3"`? I assume that by assigning it, there will be differential peak calling (in the MACS2 context) for the specified pair only?

**Comment by leepc12** [comment]
No, you should choose between "chip.ctl_fastqs" or "chip.ctl_fastqs_repX_RY".

Just define a single control with "chip.ctl_fastqs_repX_RY" then pipeline will automatically use it for all biological replicates.

"chip.ctl_fastqs_rep1_R1" : [ CONTROL_R1_FASTQ_GZ ],
"chip.ctl_fastqs_rep1_R2" : [ CONTROL_R2_FASTQ_GZ ], # for paired end cases

**Comment by dcdxy** [comment]
It might be worth noting that if there is only a single control sample (and multiple treatment samples), the control sample must be assigned to `"chip.ctl_fastqs_rep1"`. If it is assigned to `"chip.ctl_fastqs_rep2"`, the control is ignored and there is no differential processing between any pairs. This issue came up for me because I had three wild-type samples and one control sample, where the control sample was labelled as replicate 2 so it might have matched wild-type replicate 2.

**Comment by leepc12** [comment]
@dcdxy : Yes, that's true. `fastqs_rep1_R1` must be filled first regardless of given labels for multiple replicates. That is due to some limitation in WDL and design of the pipeline.
