### ISSUE TITLE
Unable to download ATACQ file when building hg19 database

### ISSUE THREAD

**Issue by dcheng1** [ENCODE-DCC/chip-seq-pipeline2#44]

**Comment by dcheng1** [comment]
I‘m trying to build hg19 using conda. Everything works good, and TSV was created, but when it tried to download ATATCQ file, I got an error: 

=== Downloading ATAQC file... (/home/dcheng1/chip-seq-pipeline2/HG19/hg19.tsv)
--2018-12-14 14:35:44--  http://mitra.stanford.edu/kundaje/genome_data/hg19/ataqc/hg19_gencode_tss_unique.bed.gz
Resolving mitra.stanford.edu... 171.65.76.236
Connecting to mitra.stanford.edu|171.65.76.236|:80... connected.
**HTTP request sent, awaiting response... 403 Forbidden
2018-12-14 14:35:45 ERROR 403: Forbidden.**

**Comment by leepc12** [comment]
1) Until it's fixed. Use this shell script.
[build_genome_data.zip](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2683690/build_genome_data.zip)

2) Or you can use `genome/download_genome_data.sh` instead. This will download (not build) genome data from ENCODE-DCC's Google Cloud servers.

**Comment by leepc12** [comment]
Already fixed.
