### ISSUE TITLE
Pipeline stalls at peak-calling steps

### ISSUE THREAD

**Issue by kdemuren** [ENCODE-DCC/chip-seq-pipeline2#47]
I've been trying to run the pipeline on the test data, and it seems to stall when it gets to peak-calling every time. I've been using qlogin on our SGE server and putting in the command manually, after activating the proper conda environment. 

command: 
`java -jar -Dconfig.file=backends/backend.conf cromwell-36.jar run chip.wdl -i ${INPUT}` 

I've attached the log.

[workflow.ed8d0870-e114-4af9-8a75-3b85625caa50.log](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2764732/workflow.ed8d0870-e114-4af9-8a75-3b85625caa50.log)

**Comment by leepc12** [comment]
Click on a "New Issue" button and choose "bug report" then you will see how to make a tar ball of logs for debugging. Please upload it here.

**Comment by kdemuren** [comment]
Tarball of the logs attached, thanks!

[debug_47_.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2770859/debug_47_.tar.gz)

**Comment by leepc12** [comment]
Is it still hanging? Your log says some peak calling jobs (macs2*, spp*) are "Done" but others are still "WaitingForReturnCode".

**Comment by kdemuren** [comment]
The log is gone (in the "cromwell-workflow-logs" folder), but there's no qc report or anything.

**Comment by kdemuren** [comment]
[debug_47_new.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2780932/debug_47_new.tar.gz)

I think I terminated the qlogin session, so I can't do the latter.

**Comment by leepc12** [comment]
You can still use `qacct`. It's a stat command for finished/failed jobs.
```
qacct -j JOB_ID
```

**Comment by kdemuren** [comment]
`qname        all.q
hostname     n2
group        bmc-boyer-nfs
owner        kdemuren
project      NONE
department   defaultdepartment
jobname      QLOGIN
jobnumber    3004475
taskid       undefined
account      sge
priority     0
qsub_time    Tue Jan 15 15:32:02 2019
start_time   -/-
end_time     -/-
granted_pe   NONE
slots        1
failed       19  : before writing exit_status
exit_status  0
ru_wallclock 0
ru_utime     0.000
ru_stime     0.000
ru_maxrss    0
ru_ixrss     0
ru_ismrss    0
ru_idrss     0
ru_isrss     0
ru_minflt    0
ru_majflt    0
ru_nswap     0
ru_inblock   0
ru_oublock   0
ru_msgsnd    0
ru_msgrcv    0
ru_nsignals  0
ru_nvcsw     0
ru_nivcsw    0
cpu          0.000
mem          0.000
io           0.000
iow          0.000
maxvmem      0.000
arid         undefined
`

**Comment by leepc12** [comment]
Did you `qlogin` with enough resources like 4 cpus, 16GB of memory, long walltime? What is your parallel environment (`qconf -spl`)?
```
qlogin -pe [YOUR_PE_NAME] 4 -l h_rt=24:00:00 -l h_vmem=16G
```

**Comment by kdemuren** [comment]
I had not done that, just set-up with a qlogin command like that (my PE was 'whole_nodes'). It's been about 4 hours, and it seems to be stuck on the spp steps again - here are the logs: 
[debug_47_v3.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2789158/debug_47_v3.tar.gz)

and here's the qacct readout: 
```
job_number:                 3005593
submission_time:            Wed Jan 23 11:42:30 2019
owner:                      kdemuren
uid:                        103035
group:                      bmc-boyer-nfs
gid:                        102080
sge_o_home:                 /home/kdemuren
sge_o_log_name:             kdemuren
sge_o_path:                 /home/kdemuren/miniconda3/bin:/home/software/r/r-3.0.2/bin:/home/software/jre/jre-1.8.0-77/bin:/home/software/bowtie2/bowtie2-2.2.0/scripts:/home/software/bowtie2/bowtie2-2.2.0:/home/software/bedtools/bedtools-2.20.1/bin:/home/sge/sge6.2u5/bin/lx24-amd64:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/454/bin:/home/kdemuren/weblogo/:/home/kdemuren/HOMER//bin/:/home/kdemuren/.bds:/home/kdemuren/bin
sge_o_shell:                /bin/bash
sge_o_workdir:              /net/bmc-pub9/data/boyerlab/users/kdemuren
sge_o_host:                 rous
account:                    sge
stderr_path_list:           NONE:NONE:/dev/null
hard resource_list:         h_rt=86400,h_vmem=16G
mail_list:                  kdemuren@rous
notify:                     FALSE
job_name:                   QLOGIN
stdout_path_list:           NONE:NONE:/dev/null
jobshare:                   0
restart:                    n
env_list:                   QRSH_PORT=rous:51533
parallel environment:  whole_nodes range: 4
usage    1:                 cpu=00:00:00, mem=0.00000 GBs, io=0.00000, vmem=N/A, maxvmem=N/A
scheduling info:            queue instance "bcc-bmc.q@n10" dropped because it is disabled
                            queue instance "all.q@n4" dropped because it is full
                            queue instance "all.q@n3" dropped because it is full
```

**Comment by kdemuren** [comment]
OK, I switched to MACS2 and it failed while on the macs2 steps (stdout attached): 
[log.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2794085/log.txt)

and tarball of logs, as before: 
[debug_47_v4.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2794092/debug_47_v4.tar.gz)

**Comment by leepc12** [comment]
Sorry about this. I will fix it (error when pipeline_type `tf` with peak_caller `macs2`) in the next release, which will be released today or tomorrow.

Please try with `"chip.peak_caller" : "macs2"` with the new release.

**Comment by kdemuren** [comment]
I did run it with the new release, and it worked! One thing though - in the included genome .tsv file, I had to change the chrom.sizes filename to match the chr19 only one included. Also, it seems like the pipeline doesn't work with cromwell-36 - when I switched to 34 it worked fine.
