### ISSUE TITLE
Job chip.macs2_ppr2:NA:1 failed

### ISSUE THREAD

**Issue by yxsee** [ENCODE-DCC/chip-seq-pipeline2#49]
I encountered the following error during the call-macs2-ppr2 step.

==> ./call-macs2_ppr2/execution/stderr <==
Traceback (most recent call last):
  File "/rbc/yixiang/anaconda2/envs/encode-chip-seq-pipeline/bin/encode_macs2_chip.py", line 223, in <module>
    main()
  File "/rbc/yixiang/anaconda2/envs/encode-chip-seq-pipeline/bin/encode_macs2_chip.py", line 215, in main
    args.chrsz, args.fraglen, args.out_dir)
  File "/rbc/yixiang/anaconda2/envs/encode-chip-seq-pipeline/bin/encode_frip.py", line 84, in frip_shifted
    write_txt(frip_qc, str(float(val1)/float(val2)))
ValueError: could not convert string to float: Differing number of BED fields encountered at line: 40330138.  Exiting...
5740102

==> ./call-macs2_pr2/shard-1/execution/stderr <==
Traceback (most recent call last):
  File "/rbc/yixiang/anaconda2/envs/encode-chip-seq-pipeline/bin/encode_macs2_chip.py", line 223, in <module>
    main()
  File "/rbc/yixiang/anaconda2/envs/encode-chip-seq-pipeline/bin/encode_macs2_chip.py", line 215, in main
    args.chrsz, args.fraglen, args.out_dir)
  File "/rbc/yixiang/anaconda2/envs/encode-chip-seq-pipeline/bin/encode_frip.py", line 84, in frip_shifted
    write_txt(frip_qc, str(float(val1)/float(val2)))
ValueError: could not convert string to float: Differing number of BED fields encountered at line: 17163938.  Exiting...
2522395

**OS/Platform and dependencies**
- Cromwell/dxWDL version: cromwell-34.jar
- Conda version: 4.3.30

[debug_49.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2805905/debug_49.tar.gz)

**Comment by yxsee** [comment]
Maybe due to this?
https://github.com/arq5x/bedtools2/issues/643

**Comment by icanwinwyz** [comment]
I think I got the same problem. I first use "bwa mem" for the alignment (150bp paired end reads), then used generated BAM files as input for your ChIP-seq pipeline. The error message I got is:

[2019-02-25 06:36:47,85] [error] WorkflowManagerActor Workflow 9e0b250d-2e84-4f1c-9a1b-ebd08a8bb42d failed (during ExecutingWorkflowState): Job chip.macs2_pr1:0:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/cromwell-executions/chip/9e0b250d-2e84-4f1c-9a1b-ebd08a8bb42d/call-macs2_pr1/shard-0/execution/stderr.
 Traceback (most recent call last):
  File "/software/chip-seq-pipeline/src/encode_macs2_chip.py", line 223, in <module>
    main()
  File "/software/chip-seq-pipeline/src/encode_macs2_chip.py", line 215, in main
    args.chrsz, args.fraglen, args.out_dir)
  File "/software/chip-seq-pipeline/src/encode_frip.py", line 84, in frip_shifted
    write_txt(frip_qc, str(float(val1)/float(val2)))
ValueError: could not convert string to float: Differing number of BED fields encountered at line: 7191088.  Exiting...
3568094

Job chip.macs2_ppr1:NA:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/cromwell-executions/chip/9e0b250d-2e84-4f1c-9a1b-ebd08a8bb42d/call-macs2_ppr1/execution/stderr.
 Traceback (most recent call last):
  File "/software/chip-seq-pipeline/src/encode_macs2_chip.py", line 223, in <module>
    main()
  File "/software/chip-seq-pipeline/src/encode_macs2_chip.py", line 215, in main
    args.chrsz, args.fraglen, args.out_dir)
  File "/software/chip-seq-pipeline/src/encode_frip.py", line 84, in frip_shifted
    write_txt(frip_qc, str(float(val1)/float(val2)))
ValueError: could not convert string to float: Differing number of BED fields encountered at line: 7191088.  Exiting...
3437900

I also checked the "stderr.submit" file and found some errors:

mkdir: cannot create directory '/common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/cromwell-executions/chip/9e0b250d-2e84-4f1c-9a1b-ebd08a8bb42d/call-macs2_ppr1/execution/glob-37a6259cc0c1dae299a7866489dff0bd': File exists
ln: failed to create hard link '/common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/cromwell-executions/chip/9e0b250d-2e84-4f1c-9a1b-ebd08a8bb42d/call-macs2_ppr1/execution/glob-37a6259cc0c1dae299a7866489dff0bd/null': File exists
ln: failed to access '*.frip.qc': No such file or directory

I attached the log file and .json file here in case you need them. Thanks.



[EFO27_H3k4me3_metadata_mem.json.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2902620/EFO27_H3k4me3_metadata_mem.json.gz)
[EFO27_H3k4me3.o187635.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2902621/EFO27_H3k4me3.o187635.gz)
[EFO27_A_H3k4me3_mem.json.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2902622/EFO27_A_H3k4me3_mem.json.gz)

**Comment by icanwinwyz** [comment]
updates:

I set the ""chip.true_rep_only" as "true" and the run can be successfully finished. I guess something wrong with the ppr/pr step. 

Also, another issue is though the suffix of narrowPeak file is ".gz", it is not a compressed file actually. I can read it directly without “gunzip”. So why we set it as ".gz"?

**Comment by yxsee** [comment]
hi @icanwinwyz, I'm sort of relieved to see that the error I encountered is not an isolated incident. In total, 2 out of 6 of my 2x150bp "bwa mem' mappped samples have this error, but 4 samples completed successfully. I am currently waiting for additional sequencing of my samples on Hi-Seq to get more reads before I try running the pipeline again.

**Comment by leepc12** [comment]
@yxsee: Please upload these files or send them to me (gmail / dropbox: leepc12 at gmail dot com).
```
U2OS_H3K27ac_DOX+_R1_trim_bwa.nodup.pr2.pooled_x_U2OS_TI_DOX+_R1_trim_bwa.nodup.pooled.pval0.01.500K.bfilt.narrowPeak.gz

/rbc/yixiang/chip-seq-pipeline2/cromwell-executions/chip/4d5820fb-1a8f-434c-bfda-297bf42dd382/call-macs2_ppr2/inputs/1736651704/U2OS_H3K27ac_DOX+_R1_trim_bwa.nodup.pr2.pooled.tagAlign.gz

/rbc/yixiang/chip-seq-pipeline2/cromwell-executions/chip/4d5820fb-1a8f-434c-bfda-297bf42dd382/call-macs2_ppr2/inputs/1719588453/hg19.chrom.sizes
```

@icanwinwyz : Can you point out which .gz file is not compressed?

Also please send me (gmail/dropbox: leepc12 at gmail dot com) these files.
```
/common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/cromwell-executions/chip/9e0b250d-2e84-4f1c-9a1b-ebd08a8bb42d/call-spr/shard-0/execution/glob-478c0ad30d0d033ce59a75ef84dab32e/EFO27_A_H3k4me3_merged.sorted.nodup.pr1.tagAlign.gz
/common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/cromwell-executions/chip/9e0b250d-2e84-4f1c-9a1b-ebd08a8bb42d/call-choose_ctl/execution/glob-7c50fbb0cd86013ba323225b21917790/ctl_for_rep1.tagAlign.gz
```

**Comment by icanwinwyz** [comment]
> @yxsee: Please upload these files or send them to me (gmail / dropbox: leepc12 at gmail dot com).
> 
> ```
> U2OS_H3K27ac_DOX+_R1_trim_bwa.nodup.pr2.pooled_x_U2OS_TI_DOX+_R1_trim_bwa.nodup.pooled.pval0.01.500K.bfilt.narrowPeak.gz
> 
> /rbc/yixiang/chip-seq-pipeline2/cromwell-executions/chip/4d5820fb-1a8f-434c-bfda-297bf42dd382/call-macs2_ppr2/inputs/1736651704/U2OS_H3K27ac_DOX+_R1_trim_bwa.nodup.pr2.pooled.tagAlign.gz
> 
> /rbc/yixiang/chip-seq-pipeline2/cromwell-executions/chip/4d5820fb-1a8f-434c-bfda-297bf42dd382/call-macs2_ppr2/inputs/1719588453/hg19.chrom.sizes
> ```
> @icanwinwyz : Can you point out which .gz file is not compressed?
> 
> Also please send me (gmail/dropbox: leepc12 at gmail dot com) these files.
> 
> ```
> /common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/cromwell-executions/chip/9e0b250d-2e84-4f1c-9a1b-ebd08a8bb42d/call-spr/shard-0/execution/glob-478c0ad30d0d033ce59a75ef84dab32e/EFO27_A_H3k4me3_merged.sorted.nodup.pr1.tagAlign.gz
> /common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/cromwell-executions/chip/9e0b250d-2e84-4f1c-9a1b-ebd08a8bb42d/call-choose_ctl/execution/glob-7c50fbb0cd86013ba323225b21917790/ctl_for_rep1.tagAlign.gz
> ```

Hi @leepc12 
Sorry for the misunderstanding, I figured out the problem about .gz file. I should use gunzip -f to decompress it. 

I tried to upload the files you asked but they are too big to be uploaded. I have shared them with you using Google Driver, please accept the invitation. Thanks.

**Comment by leepc12** [comment]
@icanwinwyz: I didn't get any invitation from you on Google Drive. Did you send an invitation to me (leepc12 at gmail dot com)?

**Comment by icanwinwyz** [comment]
> @icanwinwyz: I didn't get any invitation from you on Google Drive. Did you send an invitation to me (leepc12 at gmail dot com)?

Hi leepc12, 
I shared the folder again. Please take a look and let me know whether you received the invitation. I also emailed you the shared link.

**Comment by icanwinwyz** [comment]
Hi @leepc12 @akundaje 
Could you kindly let me know whether you got my invitation email for Google Driver or not? Since you deactivated the IDR analysis for histone, the naive overlap strategy is necessary for checking the replicates consistency. I kept getting error from this analysis. Thanks.

**Comment by leepc12** [comment]
@icanwinwyz : Yes, I downloaded those files. I am currently working on this and will let you know by end of this week.

**Comment by icanwinwyz** [comment]
Hi @leepc12 
Do you have any updates on this issue? Thanks.

**Comment by leepc12** [comment]
@icanwinwyz : I am currently working on other issues. I will look into that tomorrow or early next week.

**Comment by leepc12** [comment]
@icanwinwyz : almost figured it out. please upload the following files to that google drive directory.
```
$ find -name EFO27_A_H3k4me3_merged.sorted.nodup.tagAlign.gz
$ find -name EFO27_A_H3k4me3_merged.sorted.nodup.pr2.tagAlign.gz
```

**Comment by icanwinwyz** [comment]
@leepc12 
Uploaded! Please let me know if you need any other files. Thanks for your great help.

**Comment by leepc12** [comment]
@yxsee :  I found bunch of warnings for `bedtools bamtobed -bedpe` when converting your BAMs into BEDPEs. This resulted in an empty lines in a BED file (`.pr1.tagAlign.gz`). Are your BAMs correctly mapped as paired-end?
```
PID=17972: *****WARNING: Query K00151:421:HVC25BBXX:3:2228:7710:11231 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
PID=17972: *****WARNING: Query K00151:421:HVC25BBXX:3:2228:8369:7767 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
PID=17972: *****WARNING: Query K00151:421:HVC25BBXX:3:2228:8369:7873 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
PID=17972: *****WARNING: Query K00151:421:HVC25BBXX:3:2228:8948:32543 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
PID=17972: *****WARNING: Query K00151:421:HVC25BBXX:3:2228:8998:25562 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
PID=17972: *****WARNING: Query K00151:421:HVC25BBXX:3:2228:9790:39559 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
```

**Comment by leepc12** [comment]
@icanwinwyz : I looked at your input JSON file. You defined both FASTQs and BAMs in a single input JSON file.
```
    "chip.fastqs_rep1_R1" : [ "/common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/EFO27_A_H3k4me3_merged_R1.fastq.gz" ],
    "chip.fastqs_rep1_R2" : [ "/common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/EFO27_A_H3k4me3_merged_R2.fastq.gz" ],
    "chip.fastqs_rep2_R1" : [ "/common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/EFO27_B_H3k4me3_merged_R1.fastq.gz" ],
    "chip.fastqs_rep2_R2" : [ "/common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/EFO27_B_H3k4me3_merged_R2.fastq.gz" ],

    "chip.ctl_fastqs_rep1_R1" : [ "/common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/EFO27_25_Input_merged_R1.fastq.gz" ],
    "chip.ctl_fastqs_rep1_R2" : [ "/common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/EFO27_25_Input_merged_R2.fastq.gz" ],

    "chip.bams" : [ 
        "/common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/EFO27_A_H3k4me3_merged.sorted.bam",
        "/common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/EFO27_B_H3k4me3_merged.sorted.bam"
    ],
    "chip.ctl_bams" : [
        "/common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/EFO27_25_Input_merged.sorted.bam"
    ],
```

Then pipeline will map FASTQs but will not use BAMs generated from those FASTQs. Instead, it takes BAMs, defined in your input JSON, for all downstream analyses. I think those BAMs (`*.sorted.bam`) are not correctly mapped as paired-end. I found blank lines in your `*.pr1.tagAlign.gz`.

Please check `/common/genomics-core/data/Internal_Tests/181031_CHIP_SEQ_TEST_Michelle/fastq/temp/cromwell-executions/chip/9e0b250d-2e84-4f1c-9a1b-ebd08a8bb42d/call-filter/shard-0/execution/stdout` has any warnings like the following:
```
PID=17972: *****WARNING: Query K00151:421:HVC25BBXX:3:2228:7710:11231 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping.
```

Can you remove definition for BAMs (`"atac.bams"` and `"atac.ctl_bams"`) from your input JSON and try again? I mean starting over with your FASTQs.

**Comment by icanwinwyz** [comment]
Hi @leepc12 
Thanks for the troubleshooting. When I used FASTQ as input, everything worked fine. However, the reads are 150bp, paired-end and we think it is better to align the reads using "bwa mem" instead of aln, which is not integrated in your pipeline. So we did the alignment first to generate the BAM files using command lines shown below:

bwa mem -a -t 10 GRCh38_primary.fa $1_R1.fastq.gz $1_R2.fastq.gz > $1.sam
samtools view -bS $1.sam > $1.bam
samtools sort --output-fmt BAM -@ 10 -o $1.sorted.bam $1.bam

Then, I used these BAM as input for your pipeline but get the errors.

According to the warning you mentioned, 
"PID=17972: *****WARNING: Query K00151:421:HVC25BBXX:3:2228:7710:11231 is marked as paired, but its mate does not occur next to it in your BAM file.  Skipping."
, I think I need to sort the BAM based on the read names, right?

**Comment by leepc12** [comment]
I think you don't have to name-sort BAM. Instead, can you try with `-M` instead of `-a` for `bwa mem`. Also, please use [this](https://www.encodeproject.org/files/GRCh38_no_alt_analysis_set_GCA_000001405.15/@@download/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz) for your reference .fa. It's the same file as used in the pipeline. You can also find this file in the genome database directory.

**Comment by yxsee** [comment]
Hi @leepc12 , 
Thanks for troubleshooting. I ran `bwa mem` without any options and that might have led to single-ended alignments. I will try `-M`.

**Comment by icanwinwyz** [comment]
Hi @leepc12 ,
Thanks! I will take a try and let you know. Have a good weekend!

**Comment by icanwinwyz** [comment]
Hi @leepc12 ,
I have rerun the two tests using the BAM from "bwa mem -M" and both of test finished perfectly. I am looking forward to the next version that will integrate the "bwa mem". Thanks for you great help!

**Comment by yxsee** [comment]
hi @leepc12 , I have run `bwa mem -M` on my samples before running this pipeline and the pipeline completed successfully. Thanks for your help!
