### ISSUE TITLE
BWA mem instead of aln

### ISSUE THREAD

**Issue by yxsee** [ENCODE-DCC/chip-seq-pipeline2#50]
I am currently running the pipeline on 2 x 151 bp ChIP seq datasets and I find that the BWA 'mem' works better than the 'aln' algorithm for my datasets. In particular, the mapped ratio improved from 59% to 95%, and properly paired ratio improved from 53% to 95%. The BWA documentation seems to recommend 'mem' for reads longer than 70bp and the ENCODE ChIP seq guidelines also encourage longer read lengths (more than 50bp). Will it be possible to add the BWA aligner option into the workflow?

Thanks for your consideration!

**Comment by keoughkath** [comment]
I have this question also. Thanks!

**Comment by akundaje** [comment]
Yes good point. We should add the option to use BWA-mem and probably switch to it as the default especially since the longer PE reads are quite common now. @leepc12 discuss with Seth and lets try to add this in the next release.

**Comment by akundaje** [comment]
@leepc12 We should test the effects of switching to BWA-mem for datasets with different read lengths and SE/PE. If there isn't a significant impact on shorter read data then we should definitely switch to bwa-mem by default.

**Comment by leepc12** [comment]
Closing this because pipeline already supports `bwa mem` for PE and we will switch to a different aligner (bowtie2) for v1.3.0.
