### ISSUE TITLE
duplicate key in qc_report call input

### ISSUE THREAD

**Issue by mlin** [ENCODE-DCC/chip-seq-pipeline2#53]
The input macs2_cap_num_peak appears to be there twice

https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/a5cfe39835f9322f770a19f1ff1b777e6111cdb6/chip.wdl#L929-L938

**Comment by mlin** [comment]
cc  @cjllanwarne @orodeh @geoffjentry @geetduggal This is pretty bad for Cromwell & dxWDL to let by (if that's what's happening). I've previously seen [duplicate keys in runtime](https://github.com/DataBiosphere/topmed-workflows/blob/31ba8a714b36ada929044f2ba3d130936e6c740e/aligner/functional-equivalence-wdl/FunctionalEquivalence.wdl#L511-L513) sections but that was not as big of a deal..

**Comment by orodeh** [comment]
That's a very interesting example. I don't have code that checks for this in dxWDL, but in truth, I never considered this possibility.

**Comment by leepc12** [comment]
Thanks for reporting this. It's fixed.
