### ISSUE TITLE
Error in Test Due to Failure to Find Genome Data File

### ISSUE THREAD

**Issue by imk1** [ENCODE-DCC/chip-seq-pipeline2#58]
**Describe the bug**
I tried running the test and it failed.  I looked through the output from slurm and found that a localization via a hard link had failed.  It could not find the following file: chip-seq-pipeline2/test_genome_database/hg38_chr19_chrM/hg38.chrom.sizes.  I went into the chip-seq-pipeline2/test_genome_database/hg38_chr19_chrM directory, and the file did not exist.  I did see a file with this name: hg38_chr19_chrM.chrom.sizes.

**OS/Platform and dependencies**
- OS or Platform: Linux cluster with Ubuntu and Slurm
- Cromwell/dxWDL version: cromwell-34.jar
- Conda version: 4.5.11

**Attach error logs**
For Cromwell users only.
Run the following command line to print all non-empty STDERR outputs. This will be greatly helpful for developers to figure out the problem. Copy-paste its output to the issue page.
```
$ find -name stderr -not -empty | xargs tail -n +1
```
This did not return anything.

**Comment by leepc12** [comment]
We are sorry about this. It's fixed now. Please re-download genome database and try again.

$ wget https://storage.googleapis.com/encode-pipeline-genome-data/test_genome_database_hg38_chr19_chrM_chip.tar
$ tar xvf test_genome_database_hg38_chr19_chrM_chip.tar

**Comment by imk1** [comment]
That works.  Thanks so much!
