### ISSUE TITLE
WomLong error for slurm execution

### ISSUE THREAD

**Issue by karl616** [ENCODE-DCC/chip-seq-pipeline2#59]
**Describe the bug**
Running with slurm_singularity backend doesn't work for me. I have narrowed it down to this bug in cromwell:

https://github.com/broadinstitute/cromwell/issues/4659

Applying the suggested workaround to the memory parameter makes it work. Just to let you know if you stumbles upon something similar

**OS/Platform and dependencies**
- OS or Platform: Ubuntu 16.04
- Cromwell/dxWDL version: cromwell 38-unknown-SNAP (cromwell --version)
- Conda version: 4.5.12
- singularity version: 2.6.1-dist

**Attach error logs**
Same/similar as reported in the cromwell bug above

3) (OPTIONAL) Run the following command to collect all logs. For developer's convenience, please add `[ISSUE_ID]` to the name of the tar ball file. This command will generate a tar ball including all debugging information. Post an issue with the tar ball (`.tar.gz`) attached.
```
$ find . -type f -name 'stdout' -or -name 'stderr' -or -name 'script' -or \
-name '*.qc' -or -name '*.txt' -or -name '*.log' -or -name '*.png' -or -name '*.pdf' \
| xargs tar -zcvf debug_[ISSUE_ID].tar.gz
```

**Comment by leepc12** [comment]
cromwell 35-37 is buggy. Please use cromwell-34 or 38.

**Comment by karl616** [comment]
This was with the bioconda version 38. (See above, I completed some more of the bug report).

In the release statement of cromwell 38 it looks like they are removing support for the wom API: 

https://github.com/broadinstitute/cromwell/releases/tag/38

Perhaps they haven't cleaned up all references yet.

I will try to revert to v34, alternatively use the workaround I found.

**Comment by leepc12** [comment]
Thanks for reporting this bug in cromwell-38. I tested `slurm_singularity` with cromwell-38 and found that the error indeed occurs. We will apply that workaround to the pipeline in the next release/hotfix.

**Comment by mepowers** [comment]
I see this same error with cromwell-45.1 when using the slurm backend on bare metal.  I was able to resolve by editing the syntax in the sbatch command in reference.conf.

Interestingly, we do not see this error with Slurm on bare metal with cromwell-29 or cromwell-36.

From cromwell.log:

![image](https://user-images.githubusercontent.com/30879508/64047623-2ade8c80-cb24-11e9-840a-74d4f1d69384.png)

Reference.conf backend provided by Broad _(causes WomLong error):_

```
SLURM {
  actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"
  config {
    runtime-attributes = """
    Int runtime_minutes = 600
    Int cpus = 2
    Int requested_memory_mb_per_core = 8000
    String queue = "short"
    """

    submit = """
        sbatch -J ${job_name} -D ${cwd} -o ${out} -e ${err} -t ${runtime_minutes} -p ${queue} \
        ${"-c " + cpus} \
        --mem-per-cpu=${requested_memory_mb_per_core} \
        --wrap "/bin/bash ${script}"
    """
    kill = "scancel ${job_id}"
    check-alive = "squeue -j ${job_id}"
    job-id-regex = "Submitted batch job (\\d+).*"
  }
}
```

Revised sbatch command syntax (works):

```
        submit = """
        sbatch -J ${job_name} -D ${cwd} -o ${out} -e ${err} -t ${runtime_minutes} -p ${queue} ${"-c " + cpu} --mem ${memory_mb} --wrap "/bin/bash ${script}"
        """
```

Instead of 

`--mem-per-cpu=${requested_memory_mb_per_core}`

inputting

`--mem ${memory_mb}`

should work (whether using the --mem-per-cpu or the --mem flag).

I'll submit this change in the cromwell docs as well.

**Comment by leepc12** [comment]
I think this is already fixed in Caper. Please use Caper.

**Comment by mepowers** [comment]
@leepc12 What's Caper?

**Comment by leepc12** [comment]
It's a Cromwell wrapper python script. Please see pipeline's documentation (README.md).

**Comment by mepowers** [comment]
@ruchim is Caper your recommended BKM for deploying Cromwell with Slurm?  I don't see it anywhere in the Cromwell docs.  

In the meantime we'll stick with the workaround above.

**Comment by leepc12** [comment]
I am closing this because it is already fixed in Caper's built-in backend.
