### ISSUE TITLE
Leveraging Cluster to Run Parts of Pipeline in Parallel

### ISSUE THREAD

**Issue by imk1** [ENCODE-DCC/chip-seq-pipeline2#61]
I am running the ChIP-seq pipeline on a slurm cluster, and I would like to use the cluster to run parts of the pipeline in parallel (like map the reads from the different replicates in parallel).  Am I correct in thinking that I need to use #SBATCH -n 2 (or > 2) in order to do this?  If so, it would be great if you could clarify this somewhere.  The current example script says:
"do not touch these settings
number of tasks and nodes are fixed at 1"
which suggests that the pipeline will fail if -n is not set to 1.
Thanks so much!

**Comment by leepc12** [comment]
It doesn't fail, but with `-n 2` you will reserve 1 additional node and just don't use that. Your SLURM admin won't like that.

Please read through the description in the example shell script. Set `NUM_CONCURRENT_JOB=` as the number of replicates then analyses for different replicates will go in parallel.

**Comment by imk1** [comment]
I want to make sure I understand this correctly: Increasing NUM_CONCURRENT_JOB will have multiple replicates run in parallel on the same node.  The pipeline will then take the number of CPUs on 1 node that is equal to NUM_CONCURRENT_JOB.  I should also make sure that NUM_CONCURRENT_JOB is less than the number of CPUs on each node of the slurm cluster.  Is that right?  Thanks!

**Comment by leepc12** [comment]
```
# max number of cpus for each pipeline
#  should be <= NUM_CONCURRENT_TASK x "atac.bowtie2_cpu" in input JSON file
#  since bowtie2 is a bottlenecking task in the pipeline
#  "atac.bowtie2_cpu" is a number of cpus per replicate
#SBATCH --cpus-per-task=2
```
NUM_CONCURRENT_TASK goes to cromwell job manager settings. Cromwell will allow only 2 tasks at the same time. Those two tasks should be bowtie2 for rep1 and bowtie2 for rep2. Number of cpus for bowtie2 task will be defined in your input JSON file like "atac.bowtie2_cpu".

If you have 3 replicates but defined NUM_CONCURRENT_TASK=2 then cromwell will hold bowtie2 for rep3 until rep1 and rep2 are done.

With NUM_CONCURRENT_TASK=2 and "atac.bowtie2_cpu" : 4, set #SBATCH --cpus-per-task=8 which is 2 x 4.

**Comment by imk1** [comment]
Now this makes sense.  Thanks for clarifying.
