### ISSUE TITLE
dcc spp callpeak error

### ISSUE THREAD

**Issue by andrewucla** [ENCODE-DCC/chip-seq-pipeline2#75]
I used conda to install dependencies and tried running the pipeline with cromwell-38. I got the following error message: 

[2019-06-13 12:11:16,40] [info] BackgroundConfigAsyncJobExecutionActor [ESC[38;5;2m60e7fe00ESC[0mchip.spp_pr2:0:1]: job id: 20957
[2019-06-13 12:11:16,40] [info] BackgroundConfigAsyncJobExecutionActor [ESC[38;5;2m60e7fe00ESC[0mchip.spp_pr2:0:1]: Status change from - to Done
[2019-06-13 12:12:29,96] [info] BackgroundConfigAsyncJobExecutionActor [ESC[38;5;2m60e7fe00ESC[0mchip.macs2:1:1]: Status change from WaitingForReturnCode to Done
[2019-06-13 12:12:30,64] [ESC[38;5;1merrorESC[0m] WorkflowManagerActor Workflow 60e7fe00-99a7-4c88-a4e4-e41bac251a21 failed (during ExecutingWorkflowState): Job chip.spp:0:1 exited with return code 2 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /gpfs/fs1/data/shenlab/lw/chip-seq-pipeline2/cromwell-executions/chip/60e7fe00-99a7-4c88-a4e4-e41bac251a21/call-spp/shard-0/execution/stderr.
 usage: ENCODE DCC spp callpeak [-h] [--chrsz CHRSZ] --fraglen FRAGLEN
                               [--cap-num-peak CAP_NUM_PEAK] --blacklist
                               BLACKLIST [--keep-irregular-chr] [--nth NTH]
                               [--out-dir OUT_DIR]
                               [--log-level {NOTSET,DEBUG,INFO,WARNING,CRITICAL,ERROR,CRITICAL}]
                               tas tas
ENCODE DCC spp callpeak: error: too few arguments

If this is a conda dependency error I can switch to singularity.

**Comment by leepc12** [comment]
This doesn't look like a Conda issue. Please post your input JSON file and full `java -jar cromwell-38.jar` command line that you used.

**Comment by andrewucla** [comment]
Thanks for the response, below are the JSON file and the full cromwell command
**The input Json:**
{
    "chip.genome_tsv" : "/data/shenlab/lw/atac-seq-pipeline/genome/hg19/hg19.tsv",
    "chip.paired_end" : true,
    
    "chip.ctl_paired_end" : true,

    "chip.fastqs_rep1_R1" : [ "/data/shenlab/shared/lihua/SPI1_chipseq/SPI1_CHIPseq/colon8_R1.fastq.gz" ],
    "chip.fastqs_rep1_R2" : [ "/data/shenlab/shared/lihua/SPI1_chipseq/SPI1_CHIPseq/colon8_R2.fastq.gz" ],
    "chip.fastqs_rep2_R1" : [ "/data/shenlab/shared/lihua/SPI1_chipseq/SPI1_CHIPseq/colon9_R1.fastq.gz" ],
    "chip.fastqs_rep2_R2" : [ "/data/shenlab/shared/lihua/SPI1_chipseq/SPI1_CHIPseq/colon9_R2.fastq.gz" ],

    "chip.title" : "SPI1_chipseq_colon",
    "chip.description" : "This is an pipeline for SPI1 chipseq of colon primary tumor",

    "chip.pipeline_type" : "tf",
    "chip.peak_caller" : "spp",

    "chip.align_only" : false,
    "chip.true_rep_only" : false,

    "chip.disable_fingerprint" : false,
    "chip.enable_count_signal_track" : false,

    "chip.xcor_pe_trim_bp" : 50,
    "chip.use_filt_pe_ta_for_xcor" : false,

    "chip.dup_marker" : "picard",

    "chip.mapq_thresh" : 30,
    "chip.no_dup_removal" : false,

    "chip.mito_chr_name" : "chrM",
    "chip.regex_filter_reads" : "chrM",
    "chip.subsample_reads" : 0,
    "chip.ctl_subsample_reads" : 0,
    "chip.xcor_subsample_reads" : 15000000,

    "chip.keep_irregular_chr_in_bfilt_peak" : false,

    "chip.always_use_pooled_ctl" : false,
    "chip.ctl_depth_ratio" : 1.2,

    "chip.macs2_cap_num_peak" : 500000,
    "chip.pval_thresh" : 0.01,
    "chip.idr_thresh" : 0.05,
    "chip.spp_cap_num_peak" : 300000,

    "chip.bwa_cpu" : 4,
    "chip.bwa_mem_mb" : 20000,
    "chip.bwa_time_hr" : 48,
    "chip.bwa_disks" : "local-disk 200 HDD",

    "chip.filter_cpu" : 2,
    "chip.filter_mem_mb" : 20000,
    "chip.filter_time_hr" : 24,
    "chip.filter_disks" : "local-disk 200 HDD",

    "chip.bam2ta_cpu" : 2,
    "chip.bam2ta_mem_mb" : 10000,
    "chip.bam2ta_time_hr" : 6,
    "chip.bam2ta_disks" : "local-disk 100 HDD",

    "chip.spr_mem_mb" : 16000,

    "chip.fingerprint_cpu" : 2,
    "chip.fingerprint_mem_mb" : 12000,
    "chip.fingerprint_time_hr" : 6,
    "chip.fingerprint_disks" : "local-disk 200 HDD",

    "chip.xcor_cpu" : 2,
    "chip.xcor_mem_mb" : 16000,
    "chip.xcor_time_hr" : 24,
    "chip.xcor_disks" : "local-disk 100 HDD",

    "chip.macs2_mem_mb" : 16000,
    "chip.macs2_time_hr" : 24,
    "chip.macs2_disks" : "local-disk 200 HDD",

    "chip.spp_cpu" : 2,
    "chip.spp_mem_mb" : 16000,
    "chip.spp_time_hr" : 72,
    "chip.spp_disks" : "local-disk 200 HDD"
}

#!/bin/bash

# do not touch these settings
#  number of tasks and nodes are fixed at 1
#SBATCH -n 1
#SBATCH --ntasks-per-node=1

# job name for pipeline
#  this name will appear when you monitor jobs with "squeue -u $USER"
#SBATCH --job-name=SPI1_colon

# walltime for your job
#  give long time enough to finish your pipeline
#  <12 hr: small/test samples
#  >24 hr: large samples
#SBATCH --time=144:00:00

# total amount of memory
#  depends on the size of your FASTQs
#  but should be <= NUM_CONCURRENT_TASK x 20GB for big samples
#  or <= NUM_CONCURRENT_TASK x 10GB for small samples
#  do not request too much memory
#  cluster will not accept your job
#SBATCH --mem=60G

# max number of cpus for each pipeline
#  should be <= NUM_CONCURRENT_TASK x "chip.bwa_cpu" in input JSON file
#  since bwa is a bottlenecking task in the pipeline
#  "chip.bwa_cpu" is a number of cpus per replicate
#SBATCH --cpus-per-task=8

# email notification for job status
#SBATCH --mail-type=END,FAIL

# load java module if it exists
module load java || true

# activate pipeline's Conda environment if Conda env exists
source activate encode-chip-seq-pipeline

# use input JSON for a small test sample
#  you make an input JSON for your own sample
#  start from any of two templates for single-ended and paired-ended samples
#  (examples/template_se.json, examples/template_pe.json)
#  do not use an input JSON file for a test sample (ENCSR936XTK)
#  it's a sample with multimapping reads
INPUT=/data/shenlab/lw/chip-seq-pipeline2/run_pipeline/SPI1/Chipseq_pe.colon.json

**Comment by andrewucla** [comment]
I think I know why...Is it because spp requires a control input, and I did not provide one? Just realized it.

**Comment by leepc12** [comment]
Yes, SPP requires controls.
