### ISSUE TITLE
cannot get the testing file to work

### ISSUE THREAD

**Issue by yinshiyi** [ENCODE-DCC/chip-seq-pipeline2#77]
i git clone the folder
cd into the folder
dont have docker or singularity
have to use conda
bash conda/uninstall_dependencies.sh
bash conda/install_dependencies.sh
conda activate encode-chip-seq-pipeline
caper run chip.wdl -i examples/caper/ENCSR936XTK_subsampled_chr19_only.json --deepcopy

Thanks very much

[metadata.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3340712/metadata.txt)

**Comment by yinshiyi** [comment]
never mind, got it to work, loving docker

**Comment by tejaswiiyyanki** [comment]
same issues. Can you help walk through the steps?
Thank you!
TJ

**Comment by leepc12** [comment]
You missed two important Conda conf steps.
```
bash conda/uninstall_dependencies.sh
bash conda/install_dependencies.sh

# You missed two steps
bash conda/config_conda_env.sh
bash conda/update_conda_env.sh

conda activate encode-chip-seq-pipeline
caper run chip.wdl -i examples/caper/ENCSR936XTK_subsampled_chr19_only.json --deepcopy
```

**Comment by leepc12** [comment]
Closing this due to long inactivity
