### ISSUE TITLE
Pipeline crashes because fragment length is negative

### ISSUE THREAD

**Issue by guma44** [ENCODE-DCC/chip-seq-pipeline2#80]
Hi,
Thank you for great pipeline! The version I am working with is 1.2.2. Some of my pipelines crash on the `macs2` step (with error `--extsize must >= 1!`). I have investigated this and it turned out that that the fragment length estimated by the `xcor` is negative (-420):
```
...
Control data: NA 
strandshift(min): -500 
strandshift(step): 5 
strandshift(max) 1500 
user-defined peak shift NA 
exclusion(min): -500 
exclusion(max): 100 
num parallel nodes: 4 
FDR threshold: 0.01 
NumPeaks Threshold: NA 
Output Directory: . 
narrowPeak output file name: NA 
regionPeak output file name: NA 
Rdata filename: NA 
...
Top 3 cross-correlation values 0.0117837272740937,0.0117782782163765,0.011773314474586 
Top 3 estimates for fragment length -420,1450,1310
Window half size 1475 
```

I noticed that this was previously reported and it was addressed in version 1.2.0:

> exclusion range for cross-correlation analysis
adding -x=min:max to run_spp.R in xcor
this will prevent xcor estimates wrong (negative) fragment len

So I modified my file to and added `"chip.xcor_exclusion_range_min": 10` to the input file. However the results was the same.

So my question is how I can prevent the negative values coming from xcor? I might not understood the purpose of the parameter so I could have used it wrongly. In the #71 there is a possible solution but I do not want to provide data to all the pipelines because I would prefer it to be calculated. As far as I understand, if the `fraglen` is provided by me the `xcor` is skipped. It would be nice that if the `xcor` fails, it would take the `fraglen` from the table. Otherwise, I need to launch the pipeline for the second time and it is a waste of time and resources.

Also for me the `macs2` as a peak caller is not of interest and the pipeline could continue even without it. 

Thanks

**Comment by leepc12** [comment]
We will fix this issue in the next release (this week or next week). Until then, you can manually specify fragment length in your input JSON.
```
"chip.fraglen": [FRAGLEN_REP1, FRAGLEN_REP2, ...],
```
`FRAGLEN_REPX` can be an integer or `none` (fragment length from xcor will be used).

**Comment by guma44** [comment]
Thank you. This is what we do when the pipeline crashes. So I will wait for the next release to test it properly.

**Comment by leepc12** [comment]
Closing this because it will be fixed in the next release.
