### ISSUE TITLE
"Failed to evaluate 'chip.macs2.tas'" when running pipeline from BAM files

### ISSUE THREAD

**Issue by amulyagarimella** [ENCODE-DCC/chip-seq-pipeline2#81]
I'm running the pipeline on a SLURM cluster with Conda version 4.6.14 and cromwell-38. I'm not entirely sure what the error is caused by, and the error is too long to post in full. I've attached the output file containing the error, as well as the debug tarball. The error does not show up in stderr.

**Error Snippet**
[2019-07-23 15:52:48,29] [ESC[38;5;1merrorESC[0m] WorkflowManagerActor Workflow 669812ad-7194-4160-ab58-5bfa9b7c8520 failed (during ExecutingWorkflow
State): java.lang.RuntimeException: Failed to evaluate 'chip.macs2.tas' (reason 1 of 1): Evaluating flatten([[ta_[i]], chosen_ctl_tas[i]]) failed: :
Failed to find index Success(WomInteger(23)) on array:

Success([[], [], [], [], [], [], [], [], [], []])

**Output**
[slurm.out.11839572.2.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3427841/slurm.out.11839572.2.txt)

[debug_81.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3427837/debug_81.tar.gz)

**Comment by leepc12** [comment]
Did you specify controls? Or is this a histone pipeline run?

**Comment by amulyagarimella** [comment]
This is for a histone pipeline run.

**Comment by leepc12** [comment]
How many replicates? Can you upload your input JSON? Pipeline can process <= 10 replicates only.

**Comment by amulyagarimella** [comment]
Since JSON files aren't compatible with GitHub, I've uploaded it in plain text. I have 53 replicates, so that might be the reason why I got the error. I would really appreciate if you could look at the output to see if there's anything else that might jump out as the reason for the error.

[input_allcontrol_bams_reproducible.json.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3428950/input_allcontrol_bams_reproducible.json.txt)

**Comment by leepc12** [comment]
Our pipeline is not designed to work with too many replicates. I would recommend run each replicate separately. I mean 53 pipelines and each pipeline with one replicate.

**Comment by amulyagarimella** [comment]
Thanks for clarifying! Would this apply even when running the pipeline from BAM files?

**Comment by leepc12** [comment]
Yes, maximum number of replicates is 10.

**Comment by amulyagarimella** [comment]
Thanks so much for your help, it worked with 10 replicates!
