### ISSUE TITLE
encode_bwa.py error

### ISSUE THREAD

**Issue by KunFang93** [ENCODE-DCC/chip-seq-pipeline2#82]
**Describe the bug**
I failed to follow the tutorial. it look like the missing out-dir for encode_bwa.py, thanks a lot!

**OS/Platform and dependencies**
- OS or Platform: CentOS 6
- Conda version: 4.6.14
- Caper version: 0.3.15

**Attach error logs**
Traceback (most recent call last):
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 246, in <module>
    main()
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 214, in main
    bwa_index_prefix, args.nth, args.out_dir)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 98, in bwa_se
    run_shell_cmd(cmd)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=64122, PGID=64122, RC=1
STDERR=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]..v
```
$ caper troubleshoot [WORKFLOW_ID_OR_METADATA_JSON_FILE]
```
[Caper] troubleshooting 3349340c-1f95-497c-8b50-9cd699c7a2ec ...
Found failures:
[
    {
        "causedBy": [
            {
                "causedBy": [],
                "message": "Job chip.bwa_R1:0:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
            },
            {
                "causedBy": [],
                "message": "Job chip.bwa_R1:1:2 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details."
            }
        ],
        "message": "Workflow failed"
    }
]

chip.bwa_R1 RetryableFailure. SHARD_IDX=0, RC=1, JOB_ID=70989, RUN_START=2019-07-29T15:08:22.205Z, RUN_END=2019-07-29T15:09:20.111Z, STDOUT=/data/kun/TF_pipeline/test/chip/3349340c-1f95-497c-8b50-9cd699c7a2ec/call-bwa_R1/shard-0/execution/stdout, STDERR=/data/kun/TF_pipeline/test/chip/3349340c-1f95-497c-8b50-9cd699c7a2ec/call-bwa_R1/shard-0/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 246, in <module>
    main()
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 214, in main
    bwa_index_prefix, args.nth, args.out_dir)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 98, in bwa_se
    run_shell_cmd(cmd)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=71241, PGID=71241, RC=1
STDERR=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[bwa_read_seq] 0.0% bases are trimmed.
[bwa_aln_core] convert to sequence coordinate... 0.28 sec
[bwa_aln_core] refine gapped alignments... 0.12 sec
[bwa_aln_core] print alignments...
STDOUT=

chip.bwa_R1 Failed. SHARD_IDX=0, RC=1, JOB_ID=71425, RUN_START=2019-07-29T15:09:22.201Z, RUN_END=2019-07-29T15:10:07.018Z, STDOUT=/data/kun/TF_pipeline/test/chip/3349340c-1f95-497c-8b50-9cd699c7a2ec/call-bwa_R1/shard-0/attempt-2/execution/stdout, STDERR=/data/kun/TF_pipeline/test/chip/3349340c-1f95-497c-8b50-9cd699c7a2ec/call-bwa_R1/shard-0/attempt-2/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 246, in <module>
    main()
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 214, in main
    bwa_index_prefix, args.nth, args.out_dir)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 98, in bwa_se
    run_shell_cmd(cmd)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=71629, PGID=71629, RC=1
STDERR=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[bwa_read_seq] 0.0% bases are trimmed.
[bwa_aln_core] convert to sequence coordinate... 0.27 sec
[bwa_aln_core] refine gapped alignments... 0.09 sec
[bwa_aln_core] print alignments...
STDOUT=

chip.bwa_R1 RetryableFailure. SHARD_IDX=1, RC=1, JOB_ID=71020, RUN_START=2019-07-29T15:08:24.207Z, RUN_END=2019-07-29T15:09:30.106Z, STDOUT=/data/kun/TF_pipeline/test/chip/3349340c-1f95-497c-8b50-9cd699c7a2ec/call-bwa_R1/shard-1/execution/stdout, STDERR=/data/kun/TF_pipeline/test/chip/3349340c-1f95-497c-8b50-9cd699c7a2ec/call-bwa_R1/shard-1/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 246, in <module>
    main()
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 214, in main
    bwa_index_prefix, args.nth, args.out_dir)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 98, in bwa_se
    run_shell_cmd(cmd)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=71285, PGID=71285, RC=1
STDERR=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[bwa_read_seq] 0.0% bases are trimmed.
[bwa_aln_core] convert to sequence coordinate... 0.28 sec
[bwa_aln_core] refine gapped alignments... 0.11 sec
[bwa_aln_core] print alignments...
STDOUT=

chip.bwa_R1 Failed. SHARD_IDX=1, RC=1, JOB_ID=71496, RUN_START=2019-07-29T15:09:32.202Z, RUN_END=2019-07-29T15:10:24.828Z, STDOUT=/data/kun/TF_pipeline/test/chip/3349340c-1f95-497c-8b50-9cd699c7a2ec/call-bwa_R1/shard-1/attempt-2/execution/stdout, STDERR=/data/kun/TF_pipeline/test/chip/3349340c-1f95-497c-8b50-9cd699c7a2ec/call-bwa_R1/shard-1/attempt-2/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 246, in <module>
    main()
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 214, in main
    bwa_index_prefix, args.nth, args.out_dir)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 98, in bwa_se
    run_shell_cmd(cmd)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=71866, PGID=71866, RC=1
STDERR=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[bwa_read_seq] 0.0% bases are trimmed.
[bwa_aln_core] convert to sequence coordinate... 0.24 sec
[bwa_aln_core] refine gapped alignments... 0.09 sec
[bwa_aln_core] print alignments...
STDOUT=

chip.bwa RetryableFailure. SHARD_IDX=0, RC=1, JOB_ID=70956, RUN_START=2019-07-29T15:08:18.210Z, RUN_END=2019-07-29T15:12:10.107Z, STDOUT=/data/kun/TF_pipeline/test/chip/3349340c-1f95-497c-8b50-9cd699c7a2ec/call-bwa/shard-0/execution/stdout, STDERR=/data/kun/TF_pipeline/test/chip/3349340c-1f95-497c-8b50-9cd699c7a2ec/call-bwa/shard-0/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 246, in <module>
    main()
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 211, in main
    bwa_index_prefix, args.nth, args.use_bwa_mem_for_pe, args.out_dir)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 162, in bwa_pe
    run_shell_cmd(cmd3)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=72252, PGID=72252, RC=1
STDERR=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
STDOUT=

chip.bwa RetryableFailure. SHARD_IDX=1, RC=1, JOB_ID=70923, RUN_START=2019-07-29T15:08:14.208Z, RUN_END=2019-07-29T15:12:25.104Z, STDOUT=/data/kun/TF_pipeline/test/chip/3349340c-1f95-497c-8b50-9cd699c7a2ec/call-bwa/shard-1/execution/stdout, STDERR=/data/kun/TF_pipeline/test/chip/3349340c-1f95-497c-8b50-9cd699c7a2ec/call-bwa/shard-1/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 246, in <module>
    main()
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 211, in main
    bwa_index_prefix, args.nth, args.use_bwa_mem_for_pe, args.out_dir)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 162, in bwa_pe
    run_shell_cmd(cmd3)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=72499, PGID=72499, RC=1
STDERR=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
STDOUT=

chip.bwa_ctl RetryableFailure. SHARD_IDX=0, RC=1, JOB_ID=70893, RUN_START=2019-07-29T15:08:10.209Z, RUN_END=2019-07-29T15:12:10.107Z, STDOUT=/data/kun/TF_pipeline/test/chip/3349340c-1f95-497c-8b50-9cd699c7a2ec/call-bwa_ctl/shard-0/execution/stdout, STDERR=/data/kun/TF_pipeline/test/chip/3349340c-1f95-497c-8b50-9cd699c7a2ec/call-bwa_ctl/shard-0/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 246, in <module>
    main()
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 211, in main
    bwa_index_prefix, args.nth, args.use_bwa_mem_for_pe, args.out_dir)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 162, in bwa_pe
    run_shell_cmd(cmd3)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=72162, PGID=72162, RC=1
STDERR=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
STDOUT=

chip.bwa_ctl RetryableFailure. SHARD_IDX=1, RC=1, JOB_ID=70872, RUN_START=2019-07-29T15:08:08.212Z, RUN_END=2019-07-29T15:11:25.106Z, STDOUT=/data/kun/TF_pipeline/test/chip/3349340c-1f95-497c-8b50-9cd699c7a2ec/call-bwa_ctl/shard-1/execution/stdout, STDERR=/data/kun/TF_pipeline/test/chip/3349340c-1f95-497c-8b50-9cd699c7a2ec/call-bwa_ctl/shard-1/execution/stderr
STDERR_CONTENTS=
Traceback (most recent call last):
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 246, in <module>
    main()
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 211, in main
    bwa_index_prefix, args.nth, args.use_bwa_mem_for_pe, args.out_dir)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_bwa.py", line 162, in bwa_pe
    run_shell_cmd(cmd3)
  File "/data/kun/TF_pipeline/chip-seq-pipeline2/src/encode_common.py", line 252, in run_shell_cmd
    raise Exception(err_str)
Exception: PID=72180, PGID=72180, RC=1
STDERR=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
STDOUT=
```

**Comment by leepc12** [comment]
`samtools` should be 1.2 for the current version of the pipeline. Please check if your base Conda enrivonment has samtools > 1.2 installed in it.

We will update samtools to 1.7 in the next release so that it can cover all versions of samtools.

**Comment by KunFang93** [comment]
> `samtools` should be 1.2 for the current version of the pipeline. Please check if your base Conda enrivonment has samtools > 1.2 installed in it.
> 
> We will update samtools to 1.7 in the next release so that it can cover all versions of samtools.

Thanks for the reply! My samtools version is 1.9. Should I downgrade it to 1.2?

Kun

**Comment by leepc12** [comment]
This happens when you have in your base Conda environment. Remove it from your base (not `encode-chip-seq-pipeline`) Conda env.
```
(base) $ conda uninstall samtools
```

**Comment by KunFang93** [comment]
I have uninstalled the base samtools but still get the same error~Thanks!

**Comment by leepc12** [comment]
Please run the following for debugging.
```
$ source activate encode-chip-seq-pipeline 
$ which conda
$ which samtools
$ which bedtools
$ which bowtie2
```

**Comment by KunFang93** [comment]
which conda: /backup/kun/software/anaconda2/bin/conda
which samtools: /backup/kun/software/miniconda3/envs/encode_pipeline/bin/samtools
which bedtools: /backup/kun/software/miniconda2/bin/bedtools
which bowtie2: /backup/kun/software/miniconda2/bin/bowtie2

**Comment by leepc12** [comment]
What is `encode_pipeline`? Did you follow the instruction on github README?

**Comment by KunFang93** [comment]
I followed this instruction but I do it in pre-create conda environment 'encode_pipeline', is there some wrong?

install Conda environment for pipeline.
$ conda/install_dependencies.sh
Initialize Conda and re-login.
$ conda init bash
$ exit
Configure pipeline's python2 and python3 environments.
$ conda/config_conda_env.sh
$ conda/config_conda_env_py3.sh
Update pipeline's Conda environment with pipeline's python source code. You need to run this step everytime you update (git pull) this pipeline.
$ conda/update_conda_env.sh

**Comment by leepc12** [comment]
You need to activate pipeline's Conda environment before running a pipeline.
```
$ source activate encode-chip-seq-pipeline
```

Check if you have it
```
$ conda env list
```

**Comment by KunFang93** [comment]
There is encode-chip-seq-pipeline but I still get the same error. 
After the failure, I decided to redo the conda install instruction, and I used 'conda remove -name encode-chip-seq-pipeline' command to remove the environment. But when I try install_dependencies.sh, it shows
conda 4.6.14
=== Found Conda ().
=== Pipeline's py3 Conda env (encode-chip-seq-pipeline-python3) already exists.
=== Please remove it first (uninstall_dependencies.sh)
however, there is no such env exist. 
Sorry for bothering again, thanks!

**Comment by KunFang93** [comment]
Redo the instruction in base conda solved this problem, thanks!
