### ISSUE TITLE
bwa mem compatible?

### ISSUE THREAD

**Issue by icanwinwyz** [ENCODE-DCC/chip-seq-pipeline2#87]
This is not an issue but a inquire. Is this version officially compatible with "bwa mem"? Or is it still experimental? How should I specify the parameters to turn on the "bwa mem" in the pipeline? Thanks.

**Comment by leepc12** [comment]
Turn this flag on in your input JSON.
```
   "chip.use_bwa_mem_for_pe": true,
```
