### ISSUE TITLE
no encode_merge_fastq.py in PATH

### ISSUE THREAD

**Issue by caldodge** [ENCODE-DCC/chip-seq-pipeline2#88]
There appears to be something missing in v1.2.2.  When we run "caper run chip.wdl -i examples/local/ENCSR936XTK_subsampled_chr19_only.json" from the git clone directory, it fails with the above error.  Is this code that should be in the Singularity image?

If I try to fix this by adding the path for "src" (which contains that program as well as others), then I get a different error.

"ENCODE DCC reproducibility QC.: error: argument --peaks-pr: expected at least one argument"

This is using the Singularity/SGE method, which worked fine for v1.1.6.

**Comment by leepc12** [comment]
You need to add `--singularity` at the end of the cmd line.
```
caper run chip.wdl -i examples/local/ENCSR936XTK_subsampled_chr19_only.json --singualrity
```
Check if the above command tries to build a local singularity image on your computer.

**Comment by caldodge** [comment]
Yes, it tries, and fails, saying "FileNotFoundError: [Errno 2] No such
file or directory: 'singularity': 'singularity'"

The strange thing is that singularity IS in the path.  Also, I already
have a singularity image of v1.2.2, so I wouldn't think building one
is necessary.


[dodgec@csclprd3 chip-seq-pipeline2-master]$ caper run chip.wdl -i
examples/local/ENCSR936XTK_subsampled_chr19_only.json --singularity
|tee ~/chip-14.txt
[CaperURI] read from local, src:
/hpc/home/dodgec/chip-seq-pipeline2-master/examples/local/ENCSR936XTK_subsampled_chr19_only.json
[Caper] building local singularity image:
/hpc/apps/singularity/images/chip-seq-pipeline-v1.2.2.simg
Traceback (most recent call last):
  File "/hpc/apps/python3/3.6.4/bin/caper", line 13, in <module>
    main()
  File "/hpc/apps/python3/3.6.4/lib/python3.6/site-packages/caper/caper.py",
line 1146, in main
    c.run()
  File "/hpc/apps/python3/3.6.4/lib/python3.6/site-packages/caper/caper.py",
line 202, in run
    input_file, tmp_dir)
  File "/hpc/apps/python3/3.6.4/lib/python3.6/site-packages/caper/caper.py",
line 665, in __create_workflow_opts_json_file
    self.__build_singularity_image(singularity)
  File "/hpc/apps/python3/3.6.4/lib/python3.6/site-packages/caper/caper.py",
line 962, in __build_singularity_image
    return check_call(cmd, env=env)
  File "/hpc/apps/python3/3.6.4/lib/python3.6/subprocess.py", line
286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/hpc/apps/python3/3.6.4/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/hpc/apps/python3/3.6.4/lib/python3.6/subprocess.py", line
709, in __init__
    restore_signals, start_new_session)
  File "/hpc/apps/python3/3.6.4/lib/python3.6/subprocess.py", line
1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'singularity':
'singularity'
[dodgec@csclprd3 chip-seq-pipeline2-master]$ which singularity
/hpc/apps/singularity/2.5.2/bin/singularity

**Comment by leepc12** [comment]
Not sure why this happened. Can you switch to Conda method?

**Comment by caldodge** [comment]
I can try. I'll let you know the results.

Sincerely,

Calvin Dodge

**Comment by caldodge** [comment]
I switched to the Conda method. I'm still getting the --peaks-pr error.  I submitted "examples/local/ENCSR936XTK_subsampled_chr19_only_sge_conda.sh"

[dodgec@csclprd1 chip-seq-pipeline2]$ cat /hpc/home/dodgec/chip-seq-pipeline2/cromwell-executions/chip/12b63cea-8ac2-4831-91c3-a04c1cec2e5f/call-reproducibility_idr/execution/stderr
usage: ENCODE DCC reproducibility QC. [-h] --peaks-pr PEAKS_PR [PEAKS_PR ...]
                                      [--peak-ppr PEAK_PPR]
                                      [--peak-type {narrowPeak,regionPeak,broadPeak,gappedPeak}]
                                      [--chrsz CHRSZ] [--keep-irregular-chr]
                                      [--prefix PREFIX] [--out-dir OUT_DIR]
                                      [--log-level {NOTSET,DEBUG,INFO,WARNING,CRITICAL,ERROR,CRITICAL}]
                                      [peaks [peaks ...]]
ENCODE DCC reproducibility QC.: error: argument --peaks-pr: expected at least one argument

**Comment by caldodge** [comment]
Is there anything else I can try here?  Why would --peaks-pr be invoked without an argument?

**Comment by leepc12** [comment]
Please use Caper. You were using an deprecated method. I think file paths defined in your input JSON are not correct.

**Comment by caldodge** [comment]
I tried using caper.  I still get "file not found errors".  This is using exactly the same input files (json, tsv) as with the v1.1.6 pipeline.  Would it help to provide the json and tsv files, and the output from the lastest run?

**Comment by leepc12** [comment]
@caldodge no, please attach a full command line, your input JSON file and output from caper.

**Comment by caldodge** [comment]
The problem appears to be that the ENCODE DCC program is being called without a peaks-pr parameter.  Where does that value come from?  Does this indicate something missing in input, or in the chip.wdl file?  We are using the git clone of the chip-seq-pipeline2-master repository.

usage: ENCODE DCC reproducibility QC. [-h] --peaks-pr PEAKS_PR [PEAKS_PR ...]
                                      [--peak-ppr PEAK_PPR]
                                      [--peak-type {narrowPeak,regionPeak,broadPeak,gappedPeak}]
                                      [--chrsz CHRSZ] [--keep-irregular-chr]
                                      [--prefix PREFIX] [--out-dir OUT_DIR]
                                      [--log-level {NOTSET,DEBUG,INFO,WARNING,CRITICAL,ERROR,CRITICAL}]
                                      [peaks [peaks ...]]
ENCODE DCC reproducibility QC.: error: argument --peaks-pr: expected at least one argument

**Comment by leepc12** [comment]
Please attach your input JSON. It seems like FASTQs definition in your input JSON is wrong. Did you defined it like the following?
```
"chip.fastqs_rep1_R1": [ ]
```

**Comment by caldodge** [comment]
Command line: 
 caper run chip.wdl -i examples/local/ENCSR936XTK_subsampled_chr19_only.json --no-build-singularity --singularity /hpc/apps/singularity/images/chip-seq-pipeline-v1.2.2.simg 

I'll attach the input JSON and output files shortly.

**Comment by caldodge** [comment]
Input file (renamed because upload function rejects JSON extension)


[ENCSR936XTK_subsampled_chr19_only.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3683198/ENCSR936XTK_subsampled_chr19_only.txt)

**Comment by caldodge** [comment]
Output from run.  stderr files available on request.

[chip-18.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3683201/chip-18.txt)

**Comment by leepc12** [comment]
That means Conda or singularity didn't work.

Your input JSON is an outdated form (with 3-dimensional FASTQ array). I will make a new release today. Please use `*.caper.json` instead (see README). Also, please update your Caper to >= 0.4.0.

**Comment by caldodge** [comment]
Thanks - the job got farther along before bombing.  Here's the current command line:

caper run chip.wdl -i ./example_input_json/caper/ENCSR936XTK_subsampled_chr19_only_caper.json --no-build-singularity --singularity /hpc/apps/singularity/images/chip-seq-pipeline-v1.3.0.simg 

.caper/default.conf is configured to use Cromwell 42.

This time the failure occurred well along the way, when an intermediate file wasn't created. Got any hints as to what is going wrong this time?
[chip-24.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3692473/chip-24.txt)
[ENCSR936XTK_subsampled_chr19_only.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3692474/ENCSR936XTK_subsampled_chr19_only.txt)

**Comment by caldodge** [comment]
I've since upgraded to caper 0.51 and the 1.3.2 version of the pipeline image, but the pipeline still fails at the same point:

ln: failed to access '/hpc/home/dodgec/chip/42cf094e-0962-42ae-beca-e958bcf59966/call-gc_bias/shard-0/execution/*.gc_plot.png': No such file or directory
ln: failed to access '/hpc/home/dodgec/chip/42cf094e-0962-42ae-beca-e958bcf59966/call-gc_bias/shard-0/execution/*.gc.txt': No such file or directory

What process would create these files? Why is it not running?

**Comment by leepc12** [comment]
That GC bias failed due to low read depth.

We changed the subsampling of that sample `ENCSR936XTK_subsampled_chr19_only_caper` from 1/67 to 1/50 (for higher read depth).

`rep1-R1.subsampled.67.fastq.gz` -> `rep1-R1.subsampled.50.fastq.gz`

Please try with a new input JSON file `example_input_json/caper/ENCSR936XTK_subsampled_chr19_only_caper.json`.

Caper will auto-re-download FASTQs.

**Comment by caldodge** [comment]
Actually, I got that result with that new input file.  Can you suggest any other steps to resolve this? Do I need to attach the output from this failed run?

**Comment by leepc12** [comment]
@caldodge: Yes. Please make a TAR ball of text files. Also, please check if your input JSON have higher read depth (`.50.`) FASTQs for rep1.

**Comment by caldodge** [comment]
Thanks.  The JSON file is the latest one from the git repository, which seems to have the depth you mentioned.  I tarred up the job output, JSON file, and all non-blank stderr and stdout files, and will attach the file.
[chip-pipeline-tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3780964/chip-pipeline-tar.gz)

**Comment by caldodge** [comment]
I grabbed the stdout file for that latest run to save you some time poking through the tarball.

[2019-10-25 19:55:02,846 INFO] ['/software/chip-seq-pipeline/src/encode_task_gc_bias.py', '--nodup-bam', '/hpc/home/dodgec/chip-20191025/chip-seq-pipeline2-master/chip/649a95c5-7b64-4e95-a0a0-c51b3d2b76b0/call-gc_bias/shard-0/inputs/-709744580/rep1-R1.subsampled.50.merged.nodup.bam', '--ref-fa', '/hpc/home/dodgec/chip-20191025/chip-seq-pipeline2-master/chip/649a95c5-7b64-4e95-a0a0-c51b3d2b76b0/call-gc_bias/shard-0/inputs/1337333342/GRCh38_no_alt_analysis_set_GCA_000001405.15.chr19_chrM.fasta.gz']
[2019-10-25 19:55:02,850 INFO] run_shell_cmd: PID=25222, PGID=25222, CMD=samtools view -h /hpc/home/dodgec/chip-20191025/chip-seq-pipeline2-master/chip/649a95c5-7b64-4e95-a0a0-c51b3d2b76b0/call-gc_bias/shard-0/inputs/-709744580/rep1-R1.subsampled.50.merged.nodup.bam | grep -v "^@RG" | sed "s/\tRG:Z:[^\t]*//" | samtools view -bo ./rep1-R1.subsampled.50.merged.nodup.no_rg.bam -
[2019-10-25 19:55:03,725 INFO] PID=25222, PGID=25222, RC=0
STDERR=
STDOUT=
[2019-10-25 19:55:03,729 INFO] run_shell_cmd: PID=25227, PGID=25227, CMD=which picard.jar
[2019-10-25 19:55:03,731 INFO] PID=25227, PGID=25227, RC=0
STDERR=
STDOUT=/software/picard.jar
Error occurred during initialization of VM
Could not allocate metaspace: 1073741824 bytes

**Comment by leepc12** [comment]
Do you have enough memory on your system (>=16GB)?

**Comment by caldodge** [comment]
The node the latest job ran on has 96GB of RAM

**Comment by leepc12** [comment]
Can you try two things:

1) Keep using Singularity method and change JAVA heap memory settings.
Add the following to your `~/.bashrc` and re-login
```
export _JAVA_OPTIONS="-Xms256M -Xmx4024M -XX:ParallelGCThreads=1"
```

2) Try with Conda/SGE method instead of Singularity one
Install Conda environment and activate it before running `qsub`

**Comment by caldodge** [comment]
We tried the Java options approach, and got the following:

#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 72 bytes for AllocateHeap
# Possible reasons:
#   The system is out of physical RAM or swap space

Note: this happened even after I changed the -Xmx value to 8024M (after it failed at 4024M). I will add a tarball of the job output and the log file mentioned in the output.

[chip-pipeline-2.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3785032/chip-pipeline-2.tar.gz)

**Comment by leepc12** [comment]
A raw JAVA command line (`java -jar cromwell-42.jar ...`) to run Cromwell failed. I think your system (and SGE) has limited settings for JAVA VM?

For the failing GC bias task, pipeline just `qsub`s with 1 cpu and 8 GB RAM and runs `java -Xmx6G` (https://github.com/ENCODE-DCC/chip-seq-pipeline2/blob/master/src/encode_task_gc_bias.py#L50) inside the task.

There is another task (`filter`) using `java -Xmx4G` but it didn't fail. So let's try with `java -Xmx4G` instead of `java -Xmx6G`. Please revert the above method 1) first. 

```
$ singularity shell /hpc/apps/singularity/images/chip-seq-pipeline-v1.3.2.simg
# inside the container
$ cd /software/chip-seq-pipeline/src
# edit line 50 of encode_task_gc_bias.py
# use your preferred text editor
# replace java -Xmx6G with java -Xmx4G
$ vi encode_task_gc_bias.py
```

Check if that code change is permanent inside the container.
```
$ singularity exec /hpc/apps/singularity/images/chip-seq-pipeline-v1.3.2.simg cat /software/chip-seq-pipeline/src/encode_task_gc_bias.py | grep java
```

**Comment by caldodge** [comment]
Your suggestion gave me a clue when I tried editing the image.  I called it 1.3.2 because it was the latest version (grabbed via Docker), not because I saw that version mentioned.  It was missing encode_task_gc_bias.py, and quite a few other files.  So I used the 1.3.0 image, which definitely has all of the Python src riles.

I also think I was using the wrong Cromwell version, so I switched to using version 42.  Now, using Cromwell 42 and chip-seq-pipeline2 v1.3.0, I get much farther than I got before, but it still fails.  Should I be using a different Cromwell version, or a different chip-seq-pipeline image 
[chip-pipeline-3.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3786003/chip-pipeline-3.tar.gz)
version?  The attached tarbell contains the job output, as well as all non-blank stderr, stdout, and script files from the job.

**Comment by leepc12** [comment]
A parameter to control Java max heap will be added to the next release.

**Comment by leepc12** [comment]
Your `encode_*.py` in your image is outdated.

Two things to check

1) Any reason to use other cromwell versions?
Caper defaults to use cromwell-42. Did you specify `cromwell` in your Caper conf?

2) Your image is outdated (still at v1.3.1).
Looking at stderr of `call-call_peak` (failed task). I found `--keep-irregular-chr` which is an old parameter in v1.3.1. We removed it in v1.3.2. Please do not specify `--singularity SINGULARITY_FILE`. Just use it as a flag `--singularity` then Caper will find singularity image in a WDL file so that versions of WDL and singularity match.
