### ISSUE TITLE
Problems running on filesystems that do not allow hard-links

### ISSUE THREAD

**Issue by xiaofanjin** [ENCODE-DCC/chip-seq-pipeline2#91]
I'm running on a filesystem (beegfs) that does not allow hardlinks between different directories, and encountered the same problem as  [#63](https://github.com/ENCODE-DCC/chip-seq-pipeline2/issues/63)

Seems this is related to encode_merge_fastq.py using a hardlink when there is only one file to merge. I have successfully run the pipeline off a non-beeGFS filesystem

When I edit encode_merge_fastq.py to avoid using hard links even when 'merging' a single file, I am able to generate the expected fastq.gz files (/call-merge_fastq/shard-0/execution/R1/rep1-R1.subsampled.67.merged.fastq.gz), whereas I wasn't able to before. However, the pipeline still stalls with the following error

[error] WorkflowManagerActor Workflow f3c071d7-2d66-4047-b961-e6e9cfdaeec2 failed (during ExecutingWorkflowState): cromwell.backend.standard.StandardAsyncExecutionActor$$anon$2: Failed to evaluate job outputs:
Bad output 'merge_fastq_ctl.merged_fastq_R1': Failed to find index Success(WomInteger(0)) on array:
Success([])
0

It seems the merged fastq.gz is being created, but for some reason not found?

[output.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3691628/output.txt)

**Comment by leepc12** [comment]
Thanks for reporting this. This will be fixed in the next release (or hotfix).

**Comment by xiaofanjin** [comment]
Thanks for the updated commit. I checked out the "Pip 761 conda add missing deps" branch and built the latest singularity image as a sandbox folder, copying scripts over from the git repo's /src/ folder into the container's /software/chip-seq-pipeline/src/ folder (to avoid dependency errors with new encode_task_merge_fastq.py vs old encode_merge_fastq.py naming scheme). I then ran the tutorial example json using this singularity sandbox image, but the script still stalls with the error I mentioned above. 

`[error] WorkflowManagerActor Workflow 8628c3dc-d7ab-40b8-b7af-99b594d95f2a failed (during ExecutingWorkflowState): cromwell.backend.standard.StandardAsyncExecutionActor$$anon$2: Failed to evaluate job outputs:
Bad output 'merge_fastq.merged_fastq_R1': Failed to find index Success(WomInteger(0)) on array:
Success([])
0
Bad output 'merge_fastq.merged_fastq_R2': Failed to find index Success(WomInteger(0)) on array:
Success([])
0`

I checked and the merged fastq softlink is being successfully created in the call-merge_fastq/shard-0/execution/R1/ folder

**Comment by leepc12** [comment]
Yes, there were some changes in name scheme.

I think you need to rebuild the container from our DEV docker image `quay.io/encode-dcc/chip-seq-pipeline:PIP-761_conda_add_missing_deps_294aa68d-dc73-4252-9091-f1bade4045c7`. This images has a corrected (soft-linking) `src/encode_task_merge_fastq` in it.

```
singularity build docker://quay.io/encode-dcc/chip-seq-pipeline:PIP-761_conda_add_missing_deps_294aa68d-dc73-4252-9091-f1bade4045c7
```

Can you also try with Conda method?

**Comment by xiaofanjin** [comment]
Thanks for pointing me to the dev docker image, it fixed the naming issues. I still run into the failed to evaluate job outputs error, both with Conda and singularity. I wonder if there is some localization setting with cromwell that needs to be changed to help recognize the newly created link?

**Comment by leepc12** [comment]
@xiaofanjin: Can I get the exact error message (including log files)? I tested soft-linking on multiple platforms but it worked.

No, i don't think you need additional localization settings for Cromwell.

**Comment by xiaofanjin** [comment]
I attached the output here. 
[output.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3715089/output.txt)

also tar.gz of the output folder
[d1de6826-d2aa-4cea-888b-65790de2d09d.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3715088/d1de6826-d2aa-4cea-888b-65790de2d09d.tar.gz)

I don't know what is going on with beegfs that is preventing the merged.fastq.gz output symlinks from being recognized by the pipeline. I have also tried to modify the encode_merge_fastqs.py code so it creates an actual fastq.gz file (rather than link) and still the same error arises despite an actual merged.fastq.gz file being created successfully. I'm not sure if this is related to the beegfs hardlink restriction in some way, or another quirk with beegfs.

I also don't see this error when running the pipeline (both master and PIP761 branches, i.e. hard links and soft links) on a non-beegfs filesystem. However, it would still be helpful to get this working on beegfs as that is the filesystem our hpc cluster uses. Thanks for your help looking into this

**Comment by leepc12** [comment]
This will be fixed in the next release (today or early next week). We will completely remove file-linking (soft/hard) and intermediate FASTQs (on `R1/` and `R2/`) from the pipeline.

**Comment by xiaofanjin** [comment]
Thanks for the update, I tried the updated pipeline and it now progresses further - the merge fastq stage proceeds, but it stalls with failed output evaluation of call-align outputs. As before, the files are successfully being created in the output folder, but not being recognized by downstream tasks.

`WorkflowManagerActor Workflow 666e41d2-5460-4952-8385-e1c0a77a2724 failed (during ExecutingWorkflowState): cromwell.backend.standard.StandardAsyncExecutionActor$$anon$2: Failed to evaluate job outputs:
Bad output 'align.bam': Failed to find index Success(WomInteger(0)) on array:
Success([])
0
Bad output 'align.bai': Failed to find index Success(WomInteger(0)) on array:
Success([])
0
Bad output 'align.samstat_qc': Failed to find index Success(WomInteger(0)) on array:
Success([])
0
Bad output 'align.read_len_log': Failed to find index Success(WomInteger(0)) on array:
Success([])
0`

[chipOutput.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3745963/chipOutput.txt)

My understanding is that the workflow now combines merge fastq with align into a single task within cromwell, and this allows the downstream 'align' to recognize the outputs from merge-fastq. However for some reason output->input passing between distinct tasks remains problematic, even though the output files are being created successfully. Could this be a cromwell-related issue with the filesystem?

**Comment by leepc12** [comment]
Please make a TAR ball on /wynton/home/pollard/xiaofanj/chip-seq-pipeline2/chip/248a8b69-5c07-4a82-8c80-e928fac2bd18.

```
cd /wynton/home/pollard/xiaofanj/chip-seq-pipeline2/chip/248a8b69-5c07-4a82-8c80-e928fac2bd18
find . -type f -name 'stdout' -or -name 'stderr' -or -name 'script' -or \
-name '*.qc' -or -name '*.txt' -or -name '*.log' -or -name '*.png' -or -name '*.pdf' \
| xargs tar -zcvf debug_atac_91.tar.gz
```

**Comment by xiaofanjin** [comment]
Thanks for looking into this, tarball is attached.

[debug_atac_91.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3748377/debug_atac_91.tar.gz)

**Comment by leepc12** [comment]
All tasks are done successfully but Cromwell failed to glob outputs correctly. It's also a hard-linking issue. Cromwell (not Caper nor the pipeline) always hard-links globbed outputs (at least for version 42). This looks like a Cromwell issue (https://github.com/broadinstitute/cromwell/issues/3876).

Can you try with the latest Crowmell 47? add the following to your `~/.caper/default.conf`.
```
cromwell=https://github.com/broadinstitute/cromwell/releases/download/47/cromwell-47.jar
```

Also, can you install Singularity on your system?

**Comment by xiaofanjin** [comment]
Thanks for pointing out the issue with hardlinks in cromwell's glob outputs, the latest release of cromwell still appears to use hardlinks. I was able to resolve the problem by downloading the cromwell [source code](https://github.com/broadinstitute/cromwell), modifying the [globLinkCommand](https://github.com/broadinstitute/cromwell/blob/develop/backend/src/main/scala/cromwell/backend/standard/StandardAsyncExecutionActor.scala#L246) to use soft instead of hard links:
`.getOrElse("( ln -sL GLOB_PATTERN GLOB_DIRECTORY 2> /dev/null ) || ( ln -s GLOB_PATTERN GLOB_DIRECTORY )")` 
and building a new cromwell jar file as per their [instructions](https://cromwell.readthedocs.io/en/develop/developers/Building/). After updating `~/.caper/default.conf` to use this newly built jar, the workflow proceeded as expected

**Comment by leepc12** [comment]
That sounds good. It would be great if you can make a PR for Cromwell on their repo.
