### ISSUE TITLE
Issue with pdf2png within encode_task_xcor.py

### ISSUE THREAD

**Issue by schafferde** [ENCODE-DCC/chip-seq-pipeline2#96]
**Describe the bug**
The pipeline fails with an error message describing a failure in the pdf2png function of encode_task_xcor.py. I have verified that my copy of ghostscript, which the function seems to use, works.

**OS/Platform and dependencies**
- OS or Platform: RedHat 7
- Conda version: 4.7.10
- Caper version: 0.4.1

**Attach error logs**
Caper users:
Caper automatically run troubleshooter for failed workflows. If not and If you ran a Caper server and then get workflow_id of your failed workflow with `caper list`. Or directory use a `metadata.json` file on Cromwell's output directory
```
Error log attached.

[pipeline_error.log](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3741525/pipeline_error.log)

**Comment by leepc12** [comment]
Can you try with container-based methods (`--singularity` or `--docker`) if you have Singularity or Docker installed on your system? You don't need to activate Conda environemnt for these.

If you want to keep using Conda method. run the following for debugging.
```
$ conda activate encode-chip-seq-pipeline
$ which gs
$ gs --help
```

Also, need to see contents of your output folder.
```
$ ls -l /home/dschaffe/chipseq/test/chip/4eee28ad-76a5-4ff5-8cb6-46eaaaf1ce1e/call-xcor/shard-0/execution
```

**Comment by schafferde** [comment]
Thanks for following up!
After some investigation, I was able to resolve the problem by updating my version of ghostscript from 8.70 to 9.22. Therefore, I am closing this issue.
