### ISSUE TITLE
Errors when running the pipeline with PBS

### ISSUE THREAD

**Issue by haowenz** [ENCODE-DCC/chip-seq-pipeline2#97]
I run the pipeline with pbs and got some errors. The bash file to submit the job and the error messages are attached. It seems that the environment variables didn't pass even with "-V" specified. Please help with the issue.

Thanks,
Haowen Zhang

**OS/Platform and dependencies**
- OS or Platform: PBS
- Conda version: conda 4.7.12
- Caper version: 0.4.1

**Comment by leepc12** [comment]
I think `conda activate` does not work correctly in a BASH script.
Check if `source activate encode-chip-seq-pipeline` works.
```
$ which activate
/users/leepc12/miniconda3/bin/activate
```
If not, find an executable `activate` on your base conda environment's bin directory and `chmod +x` it.

Replace `conda activate` with `source activate` and try again.

**Comment by leepc12** [comment]
Also, please try with Singularity if your system has it.

**Comment by haowenz** [comment]
Unfortunately, we don't have Singularity. I tried what you suggest and got the following errors.

```
(encode-chip-seq-pipeline) [hzhang639@login7-d1 execution]$ conda deactivate
(base) [hzhang639@login7-d1 execution]$ which activate
~/data/miniconda3/bin/activate
(base) [hzhang639@login7-d1 execution]$ echo $PATH
/nv/hswarm1/hzhang639/data/miniconda3/bin:/nv/hswarm1/hzhang639/data/miniconda3/condabin:/nv/hswarm1/hzhang639/data/local/cmake/3.14.3/bin:/usr/local/pacerepov2/gcc/7.3.0/bin:/opt/torque/current/sbin:/opt/torque/current/bin:/usr/bin:/opt/pace/bin:/opt/pace/sbin:/usr/lpp/mmfs/bin:/opt/moab/current/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/nv/hswarm1/hzhang639/bin
(base) [hzhang639@login7-d1 execution]$ source activate encode-chip-seq-pipeline
(encode-chip-seq-pipeline) [hzhang639@login7-d1 execution]$ echo $PATH
/nv/hswarm1/hzhang639/data/miniconda3/envs/encode-chip-seq-pipeline/bin:/nv/hswarm1/hzhang639/data/miniconda3/condabin:/nv/hswarm1/hzhang639/data/local/cmake/3.14.3/bin:/usr/local/pacerepov2/gcc/7.3.0/bin:/opt/torque/current/sbin:/opt/torque/current/bin:/usr/bin:/opt/pace/bin:/opt/pace/sbin:/usr/lpp/mmfs/bin:/opt/moab/current/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/nv/hswarm1/hzhang639/bin
(encode-chip-seq-pipeline) [hzhang639@login7-d1 execution]$ conda deactivate
(base) [hzhang639@login7-d1 execution]$ conda activate encode-chip-seq-pipeline
(encode-chip-seq-pipeline) [hzhang639@login7-d1 execution]$ echo $PATH
/nv/hswarm1/hzhang639/data/miniconda3/envs/encode-chip-seq-pipeline/bin:/nv/hswarm1/hzhang639/data/miniconda3/condabin:/nv/hswarm1/hzhang639/data/local/cmake/3.14.3/bin:/usr/local/pacerepov2/gcc/7.3.0/bin:/opt/torque/current/sbin:/opt/torque/current/bin:/usr/bin:/opt/pace/bin:/opt/pace/sbin:/usr/lpp/mmfs/bin:/opt/moab/current/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/nv/hswarm1/hzhang639/bin
```

Actually the path to conda bin is gone after activate the environment no matter using source or conda activate. I guess these information may give you some idea how to fix the problem.

**Comment by leepc12** [comment]
Don't mix conda activate/deactivate with source activate/deactivate. Please follow Conda-related instruction in the document.

I think you pipeline's Conda environment was not installed correctly. Did you see success message after you install it (`scripts/install_conda_env.sh`)?

Please try this for debugging:
```
$ source activate encode-chip-seq-pipeline
$ which bowtie2
$ which encode_task_qc_report.py
$ which conda
```

**Comment by haowenz** [comment]
I remember I got a success message after installation. I just tried these with a new session.
```
(base) [hzhang639@rich133-g13-33-r ~]$ source activate encode-chip-seq-pipeline
(encode-chip-seq-pipeline) [hzhang639@rich133-g13-33-r ~]$ which bowtie2
~/data/miniconda3/envs/encode-chip-seq-pipeline/bin/bowtie2
(encode-chip-seq-pipeline) [hzhang639@rich133-g13-33-r ~]$ which encode_task_qc_report.py
~/data/miniconda3/envs/encode-chip-seq-pipeline/bin/encode_task_qc_report.py
(encode-chip-seq-pipeline) [hzhang639@rich133-g13-33-r ~]$ which conda
~/data/miniconda3/condabin/conda
```

**Comment by leepc12** [comment]
It looks like your Conda env is installed correctly. Can you add `source activate encode-chip-seq-pipeline` to the bottom of your `~/.bashrc` and try again?

**Comment by haowenz** [comment]
Thanks! I didn't see the same error immediately and it actually got some job done. Thus I assume it will work.
```
2019-10-23 00:36:00,226 INFO  - DispatchedConfigAsyncJobExecutionActor [UUID(4693f237)chip.pool_ta_ctl:NA:1]: Status change from WaitingForReturnCode to Done
147 2019-10-23 00:37:05,060 INFO  - DispatchedConfigAsyncJobExecutionActor [UUID(4693f237)chip.spr:0:1]: Status change from WaitingForReturnCode to Done
148 2019-10-23 00:37:25,946 INFO  - DispatchedConfigAsyncJobExecutionActor [UUID(4693f237)chip.pool_ta:NA:1]: Status change from WaitingForReturnCode to Done
```

But this seems not to be an ideal solution since the encode-chip-seq-pipeline environment will be activated once I login. It would be nice if there are better solutions. Actually I am even not sure whether this is a bug of your program or a problem of PBS on the server I used. Anyway, thanks again for the help!

**Comment by leepc12** [comment]
That looks like an issue of PBS since it does not respect the important parameter `-V`. Our pipeline assumes that `qsub -V` works.
